
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file ActuatorOutputs.msg */


#include <rtdbg.h>
#include <inttypes.h>
#include <hrtimer.h>
#include <topics/uORBTopics.hpp>
#include <topics/actuator_outputs.h>

constexpr char __orb_actuator_outputs_fields[] = "\x89 timestamp;\x88 noutputs;\x8a[16] output;\x86[4] _padding0;";

ORB_DEFINE(actuator_outputs, struct actuator_outputs_s, 76, __orb_actuator_outputs_fields, static_cast<uint8_t>(ORB_ID::actuator_outputs));
ORB_DEFINE(actuator_outputs_sim, struct actuator_outputs_s, 76, __orb_actuator_outputs_fields, static_cast<uint8_t>(ORB_ID::actuator_outputs_sim));
ORB_DEFINE(actuator_outputs_debug, struct actuator_outputs_s, 76, __orb_actuator_outputs_fields, static_cast<uint8_t>(ORB_ID::actuator_outputs_debug));


void print_message(const orb_metadata *meta, const actuator_outputs_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
