
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file ActuatorOutputs.msg */


#pragma once


#include <uORB.h>


#ifndef __cplusplus
#define ACTUATOR_OUTPUTS_NUM_ACTUATOR_OUTPUTS 16
#define ACTUATOR_OUTPUTS_NUM_ACTUATOR_OUTPUT_GROUPS 4

#endif


#ifdef __cplusplus
struct __EXPORT actuator_outputs_s {
#else
struct actuator_outputs_s {
#endif
	uint64_t timestamp;
	uint32_t noutputs;
	float output[16];
	uint8_t _padding0[4]; // required for logger


#ifdef __cplusplus
	static constexpr uint8_t NUM_ACTUATOR_OUTPUTS = 16;
	static constexpr uint8_t NUM_ACTUATOR_OUTPUT_GROUPS = 4;

#endif
};

#ifdef __cplusplus
namespace nextpilot {
	namespace msg {
		using ActuatorOutputs = actuator_outputs_s;
	} // namespace msg
} // namespace nextpilot
#endif

/* register this as object request broker structure */
ORB_DECLARE(actuator_outputs);
ORB_DECLARE(actuator_outputs_sim);
ORB_DECLARE(actuator_outputs_debug);


#ifdef __cplusplus
void print_message(const orb_metadata *meta, const actuator_outputs_s& message);
#endif
