
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file AirspeedValidated.msg */


#pragma once


#include <uORB.h>


#ifndef __cplusplus

#endif


#ifdef __cplusplus
struct __EXPORT airspeed_validated_s {
#else
struct airspeed_validated_s {
#endif
	uint64_t timestamp;
	float indicated_airspeed_m_s;
	float calibrated_airspeed_m_s;
	float true_airspeed_m_s;
	float calibrated_ground_minus_wind_m_s;
	float true_ground_minus_wind_m_s;
	bool airspeed_sensor_measurement_valid;
	int8_t selected_airspeed_index;
	uint8_t _padding0[2]; // required for logger


#ifdef __cplusplus

#endif
};

#ifdef __cplusplus
namespace nextpilot {
	namespace msg {
		using AirspeedValidated = airspeed_validated_s;
	} // namespace msg
} // namespace nextpilot
#endif

/* register this as object request broker structure */
ORB_DECLARE(airspeed_validated);


#ifdef __cplusplus
void print_message(const orb_metadata *meta, const airspeed_validated_s& message);
#endif
