
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file AutotuneAttitudeControlStatus.msg */


#include <rtdbg.h>
#include <inttypes.h>
#include <hrtimer.h>
#include <topics/uORBTopics.hpp>
#include <topics/autotune_attitude_control_status.h>

constexpr char __orb_autotune_attitude_control_status_fields[] = "\x89 timestamp;\x8a[5] coeff;\x8a[5] coeff_var;\x8a fitness;\x8a innov;\x8a dt_model;\x8a kc;\x8a ki;\x8a kd;\x8a kff;\x8a att_p;\x8a[3] rate_sp;\x8a u_filt;\x8a y_filt;\x86 state;\x86[3] _padding0;";

ORB_DEFINE(autotune_attitude_control_status, struct autotune_attitude_control_status_s, 101, __orb_autotune_attitude_control_status_fields, static_cast<uint8_t>(ORB_ID::autotune_attitude_control_status));


void print_message(const orb_metadata *meta, const autotune_attitude_control_status_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
