
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file CollisionConstraints.msg */


#include <rtdbg.h>
#include <inttypes.h>
#include <hrtimer.h>
#include <topics/uORBTopics.hpp>
#include <topics/collision_constraints.h>

constexpr char __orb_collision_constraints_fields[] = "\x89 timestamp;\x8a[2] original_setpoint;\x8a[2] adapted_setpoint;";

ORB_DEFINE(collision_constraints, struct collision_constraints_s, 24, __orb_collision_constraints_fields, static_cast<uint8_t>(ORB_ID::collision_constraints));


void print_message(const orb_metadata *meta, const collision_constraints_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
