
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file D:\nextpilot\nextpilot-flight-control-public\msgs\uorb_msgs\ControlAllocatorStatus.msg */


#include <rtdbg.h>
#include <inttypes.h>
//#include <px4_platform_common/log.h>
//#include <px4_platform_common/defines.h>
#include <topics/control_allocator_status.h>
#include <topics/uORBTopics.hpp>
#include <hrtimer.h>
//#include <lib/drivers/device/Device.hpp>
//#include <lib/matrix/matrix/math.hpp>
//#include <lib/mathlib/mathlib.h>

constexpr char __orb_control_allocator_status_fields[] = "\x89 timestamp;\x8a[3] unallocated_torque;\x8a[3] unallocated_thrust;\x87 handled_motor_failure_mask;\x8c torque_setpoint_achieved;\x8c thrust_setpoint_achieved;\x82[16] actuator_saturation;\x86[4] _padding0;";

ORB_DEFINE(control_allocator_status, struct control_allocator_status_s, 52, __orb_control_allocator_status_fields, static_cast<uint8_t>(ORB_ID::control_allocator_status));


void print_message(const orb_metadata *meta, const control_allocator_status_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
