
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file D:\nextpilot\nextpilot-flight-control-public\msgs\uorb_msgs\DebugArray.msg */


#pragma once


#include <uORB.h>


#ifndef __cplusplus
#define DEBUG_ARRAY_ARRAY_SIZE 58

#endif


#ifdef __cplusplus
struct __EXPORT debug_array_s {
#else
struct debug_array_s {
#endif
	uint64_t timestamp;
	float data[58];
	uint16_t id;
	char name[10];
	uint8_t _padding0[4]; // required for logger


#ifdef __cplusplus
	static constexpr uint8_t ARRAY_SIZE = 58;

#endif
};

#ifdef __cplusplus
namespace nextpilot {
	namespace msg {
		using DebugArray = debug_array_s;
	} // namespace msg
} // namespace nextpilot
#endif

/* register this as object request broker structure */
ORB_DECLARE(debug_array);


#ifdef __cplusplus
void print_message(const orb_metadata *meta, const debug_array_s& message);
#endif
