
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file D:\nextpilot\nextpilot-flight-control-public\msgs\uorb_msgs\DistanceSensor.msg */


#include <rtdbg.h>
#include <inttypes.h>
//#include <px4_platform_common/log.h>
//#include <px4_platform_common/defines.h>
#include <topics/distance_sensor.h>
#include <topics/uORBTopics.hpp>
#include <hrtimer.h>
//#include <lib/drivers/device/Device.hpp>
//#include <lib/matrix/matrix/math.hpp>
//#include <lib/mathlib/mathlib.h>

constexpr char __orb_distance_sensor_fields[] = "\x89 timestamp;\x88 device_id;\x8a min_distance;\x8a max_distance;\x8a current_distance;\x8a variance;\x8a h_fov;\x8a v_fov;\x8a[4] q;\x82 signal_quality;\x86 type;\x86 orientation;\x86[1] _padding0;";

ORB_DEFINE(distance_sensor, struct distance_sensor_s, 55, __orb_distance_sensor_fields, static_cast<uint8_t>(ORB_ID::distance_sensor));


void print_message(const orb_metadata *meta, const distance_sensor_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
