
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file EscStatus.msg */


#include <rtdbg.h>
#include <inttypes.h>
#include <hrtimer.h>
#include <topics/uORBTopics.hpp>
#include <topics/esc_status.h>

constexpr char __orb_esc_status_fields[] = "\x89 timestamp;\x87 counter;\x86 esc_count;\x86 esc_connectiontype;\x86 esc_online_flags;\x86 esc_armed_flags;\x86[2] _padding0;esc_report[8] esc;";

ORB_DEFINE(esc_status, struct esc_status_s, 336, __orb_esc_status_fields, static_cast<uint8_t>(ORB_ID::esc_status));


void print_message(const orb_metadata *meta, const esc_status_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
