
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file EscReport.msg */


#include <rtdbg.h>
#include <inttypes.h>
#include <hrtimer.h>
#include <topics/uORBTopics.hpp>
#include <topics/esc_report.h>

constexpr char __orb_esc_report_fields[] = "\x89 timestamp;\x88 esc_errorcount;\x84 esc_rpm;\x8a esc_voltage;\x8a esc_current;\x8a esc_temperature;\x87 failures;\x86 esc_address;\x86 esc_cmdcount;\x86 esc_state;\x86 actuator_function;\x82 esc_power;\x86[5] _padding0;";

ORB_DEFINE(esc_report, struct esc_report_s, 35, __orb_esc_report_fields, static_cast<uint8_t>(ORB_ID::esc_report));


void print_message(const orb_metadata *meta, const esc_report_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
