
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file D:\nextpilot\nextpilot-flight-control-public\msgs\uorb_msgs\EstimatorBias3d.msg */


#include <rtdbg.h>
#include <inttypes.h>
//#include <px4_platform_common/log.h>
//#include <px4_platform_common/defines.h>
#include <topics/estimator_bias3d.h>
#include <topics/uORBTopics.hpp>
#include <hrtimer.h>
//#include <lib/drivers/device/Device.hpp>
//#include <lib/matrix/matrix/math.hpp>
//#include <lib/mathlib/mathlib.h>

constexpr char __orb_estimator_bias3d_fields[] = "\x89 timestamp;\x89 timestamp_sample;\x88 device_id;\x8a[3] bias;\x8a[3] bias_var;\x8a[3] innov;\x8a[3] innov_var;\x8a[3] innov_test_ratio;";

ORB_DEFINE(estimator_bias3d, struct estimator_bias3d_s, 80, __orb_estimator_bias3d_fields, static_cast<uint8_t>(ORB_ID::estimator_bias3d));
ORB_DEFINE(estimator_ev_pos_bias, struct estimator_bias3d_s, 80, __orb_estimator_bias3d_fields, static_cast<uint8_t>(ORB_ID::estimator_ev_pos_bias));


void print_message(const orb_metadata *meta, const estimator_bias3d_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
