
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file D:\nextpilot\nextpilot-flight-control-public\msgs\uorb_msgs\EstimatorSensorBias.msg */


#include <rtdbg.h>
#include <inttypes.h>
//#include <px4_platform_common/log.h>
//#include <px4_platform_common/defines.h>
#include <topics/estimator_sensor_bias.h>
#include <topics/uORBTopics.hpp>
#include <hrtimer.h>
//#include <lib/drivers/device/Device.hpp>
//#include <lib/matrix/matrix/math.hpp>
//#include <lib/mathlib/mathlib.h>

constexpr char __orb_estimator_sensor_bias_fields[] = "\x89 timestamp;\x89 timestamp_sample;\x88 gyro_device_id;\x8a[3] gyro_bias;\x8a gyro_bias_limit;\x8a[3] gyro_bias_variance;\x88 accel_device_id;\x8a[3] accel_bias;\x8a accel_bias_limit;\x8a[3] accel_bias_variance;\x88 mag_device_id;\x8a[3] mag_bias;\x8a mag_bias_limit;\x8a[3] mag_bias_variance;\x8c gyro_bias_valid;\x8c gyro_bias_stable;\x8c accel_bias_valid;\x8c accel_bias_stable;\x8c mag_bias_valid;\x8c mag_bias_stable;\x86[2] _padding0;";

ORB_DEFINE(estimator_sensor_bias, struct estimator_sensor_bias_s, 118, __orb_estimator_sensor_bias_fields, static_cast<uint8_t>(ORB_ID::estimator_sensor_bias));


void print_message(const orb_metadata *meta, const estimator_sensor_bias_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
