
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file EstimatorBias.msg */


#include <rtdbg.h>
#include <inttypes.h>
#include <hrtimer.h>
#include <topics/uORBTopics.hpp>
#include <topics/estimator_bias.h>

constexpr char __orb_estimator_bias_fields[] = "\x89 timestamp;\x89 timestamp_sample;\x88 device_id;\x8a bias;\x8a bias_var;\x8a innov;\x8a innov_var;\x8a innov_test_ratio;";

ORB_DEFINE(estimator_baro_bias, struct estimator_bias_s, 40, __orb_estimator_bias_fields, static_cast<uint8_t>(ORB_ID::estimator_baro_bias));
ORB_DEFINE(estimator_gnss_hgt_bias, struct estimator_bias_s, 40, __orb_estimator_bias_fields, static_cast<uint8_t>(ORB_ID::estimator_gnss_hgt_bias));
ORB_DEFINE(estimator_rng_hgt_bias, struct estimator_bias_s, 40, __orb_estimator_bias_fields, static_cast<uint8_t>(ORB_ID::estimator_rng_hgt_bias));


void print_message(const orb_metadata *meta, const estimator_bias_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
