
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file D:\nextpilot\nextpilot-flight-control-public\msgs\uorb_msgs\Event.msg */


#pragma once


#include <uORB.h>


#ifndef __cplusplus
#define EVENT_ORB_QUEUE_LENGTH 16

#endif


#ifdef __cplusplus
struct __EXPORT event_s {
#else
struct event_s {
#endif
	uint64_t timestamp;
	uint32_t id;
	uint16_t event_sequence;
	uint8_t arguments[25];
	uint8_t log_levels;


#ifdef __cplusplus
	static constexpr uint8_t ORB_QUEUE_LENGTH = 16;

#endif
};

#ifdef __cplusplus
namespace nextpilot {
	namespace msg {
		using Event = event_s;
	} // namespace msg
} // namespace nextpilot
#endif

/* register this as object request broker structure */
ORB_DECLARE(event);


#ifdef __cplusplus
void print_message(const orb_metadata *meta, const event_s& message);
#endif
