
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file FailureDetectorStatus.msg */


#include <rtdbg.h>
#include <inttypes.h>
#include <hrtimer.h>
#include <topics/uORBTopics.hpp>
#include <topics/failure_detector_status.h>

constexpr char __orb_failure_detector_status_fields[] = "\x89 timestamp;\x8a imbalanced_prop_metric;\x87 motor_failure_mask;\x8c fd_roll;\x8c fd_pitch;\x8c fd_alt;\x8c fd_ext;\x8c fd_arm_escs;\x8c fd_battery;\x8c fd_imbalanced_prop;\x8c fd_motor;\x86[2] _padding0;";

ORB_DEFINE(failure_detector_status, struct failure_detector_status_s, 22, __orb_failure_detector_status_fields, static_cast<uint8_t>(ORB_ID::failure_detector_status));


void print_message(const orb_metadata *meta, const failure_detector_status_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
