
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file FailureDetectorStatus.msg */

#pragma once

#include <uORB.h>

#ifndef __cplusplus
#endif // __cplusplus


#ifdef __cplusplus
struct __EXPORT failure_detector_status_s {
#else
struct failure_detector_status_s {
#endif // __cplusplus
	uint64_t timestamp;
	float imbalanced_prop_metric;
	uint16_t motor_failure_mask;
	bool fd_roll;
	bool fd_pitch;
	bool fd_alt;
	bool fd_ext;
	bool fd_arm_escs;
	bool fd_battery;
	bool fd_imbalanced_prop;
	bool fd_motor;
	uint8_t _padding0[2]; // required for logger

#ifdef __cplusplus
#endif // __cplusplus
};

#ifdef __cplusplus
namespace nextpilot {
	namespace msg {
		using FailureDetectorStatus = failure_detector_status_s;
	} // namespace msg
} // namespace nextpilot
#endif // __cplusplus

/* register this as object request broker structure */
ORB_DECLARE(failure_detector_status);

#ifdef __cplusplus
void print_message(const orb_metadata *meta, const failure_detector_status_s& message);
#endif // __cplusplus
