
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file D:\nextpilot\nextpilot-flight-control-public\msgs\uorb_msgs\FollowTargetStatus.msg */


#pragma once


#include <uORB.h>


#ifndef __cplusplus

#endif


#ifdef __cplusplus
struct __EXPORT follow_target_status_s {
#else
struct follow_target_status_s {
#endif
	uint64_t timestamp;
	float tracked_target_course;
	float follow_angle;
	float orbit_angle_setpoint;
	float angular_rate_setpoint;
	float desired_position_raw[3];
	float gimbal_pitch;
	bool in_emergency_ascent;
	uint8_t _padding0[7]; // required for logger


#ifdef __cplusplus

#endif
};

#ifdef __cplusplus
namespace nextpilot {
	namespace msg {
		using FollowTargetStatus = follow_target_status_s;
	} // namespace msg
} // namespace nextpilot
#endif

/* register this as object request broker structure */
ORB_DECLARE(follow_target_status);


#ifdef __cplusplus
void print_message(const orb_metadata *meta, const follow_target_status_s& message);
#endif
