
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file GimbalDeviceAttitudeStatus.msg */


#pragma once


#include <uORB.h>


#ifndef __cplusplus
#define GIMBAL_DEVICE_ATTITUDE_STATUS_DEVICE_FLAGS_RETRACT 1
#define GIMBAL_DEVICE_ATTITUDE_STATUS_DEVICE_FLAGS_NEUTRAL 2
#define GIMBAL_DEVICE_ATTITUDE_STATUS_DEVICE_FLAGS_ROLL_LOCK 4
#define GIMBAL_DEVICE_ATTITUDE_STATUS_DEVICE_FLAGS_PITCH_LOCK 8
#define GIMBAL_DEVICE_ATTITUDE_STATUS_DEVICE_FLAGS_YAW_LOCK 16

#endif


#ifdef __cplusplus
struct __EXPORT gimbal_device_attitude_status_s {
#else
struct gimbal_device_attitude_status_s {
#endif
	uint64_t timestamp;
	float q[4];
	float angular_velocity_x;
	float angular_velocity_y;
	float angular_velocity_z;
	uint32_t failure_flags;
	uint16_t device_flags;
	uint8_t target_system;
	uint8_t target_component;
	bool received_from_mavlink;
	uint8_t _padding0[3]; // required for logger


#ifdef __cplusplus
	static constexpr uint16_t DEVICE_FLAGS_RETRACT = 1;
	static constexpr uint16_t DEVICE_FLAGS_NEUTRAL = 2;
	static constexpr uint16_t DEVICE_FLAGS_ROLL_LOCK = 4;
	static constexpr uint16_t DEVICE_FLAGS_PITCH_LOCK = 8;
	static constexpr uint16_t DEVICE_FLAGS_YAW_LOCK = 16;

#endif
};

#ifdef __cplusplus
namespace nextpilot {
	namespace msg {
		using GimbalDeviceAttitudeStatus = gimbal_device_attitude_status_s;
	} // namespace msg
} // namespace nextpilot
#endif

/* register this as object request broker structure */
ORB_DECLARE(gimbal_device_attitude_status);


#ifdef __cplusplus
void print_message(const orb_metadata *meta, const gimbal_device_attitude_status_s& message);
#endif
