
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file D:\nextpilot\nextpilot-flight-control-public\msgs\uorb_msgs\GimbalManagerSetAttitude.msg */


#include <rtdbg.h>
#include <inttypes.h>
//#include <px4_platform_common/log.h>
//#include <px4_platform_common/defines.h>
#include <topics/gimbal_manager_set_attitude.h>
#include <topics/uORBTopics.hpp>
#include <hrtimer.h>
//#include <lib/drivers/device/Device.hpp>
//#include <lib/matrix/matrix/math.hpp>
//#include <lib/mathlib/mathlib.h>

constexpr char __orb_gimbal_manager_set_attitude_fields[] = "\x89 timestamp;\x88 flags;\x8a[4] q;\x8a angular_velocity_x;\x8a angular_velocity_y;\x8a angular_velocity_z;\x86 origin_sysid;\x86 origin_compid;\x86 target_system;\x86 target_component;\x86 gimbal_device_id;\x86[3] _padding0;";

ORB_DEFINE(gimbal_manager_set_attitude, struct gimbal_manager_set_attitude_s, 45, __orb_gimbal_manager_set_attitude_fields, static_cast<uint8_t>(ORB_ID::gimbal_manager_set_attitude));


void print_message(const orb_metadata *meta, const gimbal_manager_set_attitude_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
