
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file GimbalDeviceSetAttitude.msg */


#include <rtdbg.h>
#include <inttypes.h>
#include <hrtimer.h>
#include <topics/uORBTopics.hpp>
#include <topics/gimbal_device_set_attitude.h>

constexpr char __orb_gimbal_device_set_attitude_fields[] = "\x89 timestamp;\x8a[4] q;\x8a angular_velocity_x;\x8a angular_velocity_y;\x8a angular_velocity_z;\x87 flags;\x86 target_system;\x86 target_component;";

ORB_DEFINE(gimbal_device_set_attitude, struct gimbal_device_set_attitude_s, 40, __orb_gimbal_device_set_attitude_fields, static_cast<uint8_t>(ORB_ID::gimbal_device_set_attitude));


void print_message(const orb_metadata *meta, const gimbal_device_set_attitude_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
