
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file D:\nextpilot\nextpilot-flight-control-public\msgs\uorb_msgs\GimbalManagerSetManualControl.msg */


#include <rtdbg.h>
#include <inttypes.h>
//#include <px4_platform_common/log.h>
//#include <px4_platform_common/defines.h>
#include <topics/gimbal_manager_set_manual_control.h>
#include <topics/uORBTopics.hpp>
#include <hrtimer.h>
//#include <lib/drivers/device/Device.hpp>
//#include <lib/matrix/matrix/math.hpp>
//#include <lib/mathlib/mathlib.h>

constexpr char __orb_gimbal_manager_set_manual_control_fields[] = "\x89 timestamp;\x88 flags;\x8a pitch;\x8a yaw;\x8a pitch_rate;\x8a yaw_rate;\x86 origin_sysid;\x86 origin_compid;\x86 target_system;\x86 target_component;\x86 gimbal_device_id;\x86[7] _padding0;";

ORB_DEFINE(gimbal_manager_set_manual_control, struct gimbal_manager_set_manual_control_s, 33, __orb_gimbal_manager_set_manual_control_fields, static_cast<uint8_t>(ORB_ID::gimbal_manager_set_manual_control));


void print_message(const orb_metadata *meta, const gimbal_manager_set_manual_control_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
