
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file GimbalControls.msg */


#include <rtdbg.h>
#include <inttypes.h>
#include <hrtimer.h>
#include <topics/uORBTopics.hpp>
#include <topics/gimbal_controls.h>

constexpr char __orb_gimbal_controls_fields[] = "\x89 timestamp;\x89 timestamp_sample;\x8a[3] control;\x86[4] _padding0;";

ORB_DEFINE(gimbal_controls, struct gimbal_controls_s, 28, __orb_gimbal_controls_fields, static_cast<uint8_t>(ORB_ID::gimbal_controls));


void print_message(const orb_metadata *meta, const gimbal_controls_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
