
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file D:\nextpilot\nextpilot-flight-control-public\msgs\uorb_msgs\Gripper.msg */


#pragma once


#include <uORB.h>


#ifndef __cplusplus
#define GRIPPER_COMMAND_GRAB 0
#define GRIPPER_COMMAND_RELEASE 1

#endif


#ifdef __cplusplus
struct __EXPORT gripper_s {
#else
struct gripper_s {
#endif
	uint64_t timestamp;
	int8_t command;
	uint8_t _padding0[7]; // required for logger


#ifdef __cplusplus
	static constexpr int8_t COMMAND_GRAB = 0;
	static constexpr int8_t COMMAND_RELEASE = 1;

#endif
};

#ifdef __cplusplus
namespace nextpilot {
	namespace msg {
		using Gripper = gripper_s;
	} // namespace msg
} // namespace nextpilot
#endif

/* register this as object request broker structure */
ORB_DECLARE(gripper);


#ifdef __cplusplus
void print_message(const orb_metadata *meta, const gripper_s& message);
#endif
