
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file D:\nextpilot\nextpilot-flight-control-public\msgs\uorb_msgs\HealthReport.msg */


#pragma once


#include <uORB.h>


#ifndef __cplusplus

#endif


#ifdef __cplusplus
struct __EXPORT health_report_s {
#else
struct health_report_s {
#endif
	uint64_t timestamp;
	uint64_t can_arm_mode_flags;
	uint64_t can_run_mode_flags;
	uint64_t health_is_present_flags;
	uint64_t health_warning_flags;
	uint64_t health_error_flags;
	uint64_t arming_check_warning_flags;
	uint64_t arming_check_error_flags;


#ifdef __cplusplus

#endif
};

#ifdef __cplusplus
namespace nextpilot {
	namespace msg {
		using HealthReport = health_report_s;
	} // namespace msg
} // namespace nextpilot
#endif

/* register this as object request broker structure */
ORB_DECLARE(health_report);


#ifdef __cplusplus
void print_message(const orb_metadata *meta, const health_report_s& message);
#endif
