
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file HoverThrustEstimate.msg */


#pragma once


#include <uORB.h>


#ifndef __cplusplus

#endif


#ifdef __cplusplus
struct __EXPORT hover_thrust_estimate_s {
#else
struct hover_thrust_estimate_s {
#endif
	uint64_t timestamp;
	uint64_t timestamp_sample;
	float hover_thrust;
	float hover_thrust_var;
	float accel_innov;
	float accel_innov_var;
	float accel_innov_test_ratio;
	float accel_noise_var;
	bool valid;
	uint8_t _padding0[7]; // required for logger


#ifdef __cplusplus

#endif
};

#ifdef __cplusplus
namespace nextpilot {
	namespace msg {
		using HoverThrustEstimate = hover_thrust_estimate_s;
	} // namespace msg
} // namespace nextpilot
#endif

/* register this as object request broker structure */
ORB_DECLARE(hover_thrust_estimate);


#ifdef __cplusplus
void print_message(const orb_metadata *meta, const hover_thrust_estimate_s& message);
#endif
