
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file InternalCombustionEngineStatus.msg */


#pragma once


#include <uORB.h>


#ifndef __cplusplus
#define INTERNAL_COMBUSTION_ENGINE_STATUS_STATE_STOPPED 0
#define INTERNAL_COMBUSTION_ENGINE_STATUS_STATE_STARTING 1
#define INTERNAL_COMBUSTION_ENGINE_STATUS_STATE_RUNNING 2
#define INTERNAL_COMBUSTION_ENGINE_STATUS_STATE_FAULT 3
#define INTERNAL_COMBUSTION_ENGINE_STATUS_FLAG_GENERAL_ERROR 1
#define INTERNAL_COMBUSTION_ENGINE_STATUS_FLAG_CRANKSHAFT_SENSOR_ERROR_SUPPORTED 2
#define INTERNAL_COMBUSTION_ENGINE_STATUS_FLAG_CRANKSHAFT_SENSOR_ERROR 4
#define INTERNAL_COMBUSTION_ENGINE_STATUS_FLAG_TEMPERATURE_SUPPORTED 8
#define INTERNAL_COMBUSTION_ENGINE_STATUS_FLAG_TEMPERATURE_BELOW_NOMINAL 16
#define INTERNAL_COMBUSTION_ENGINE_STATUS_FLAG_TEMPERATURE_ABOVE_NOMINAL 32
#define INTERNAL_COMBUSTION_ENGINE_STATUS_FLAG_TEMPERATURE_OVERHEATING 64
#define INTERNAL_COMBUSTION_ENGINE_STATUS_FLAG_TEMPERATURE_EGT_ABOVE_NOMINAL 128
#define INTERNAL_COMBUSTION_ENGINE_STATUS_FLAG_FUEL_PRESSURE_SUPPORTED 256
#define INTERNAL_COMBUSTION_ENGINE_STATUS_FLAG_FUEL_PRESSURE_BELOW_NOMINAL 512
#define INTERNAL_COMBUSTION_ENGINE_STATUS_FLAG_FUEL_PRESSURE_ABOVE_NOMINAL 1024
#define INTERNAL_COMBUSTION_ENGINE_STATUS_FLAG_DETONATION_SUPPORTED 2048
#define INTERNAL_COMBUSTION_ENGINE_STATUS_FLAG_DETONATION_OBSERVED 4096
#define INTERNAL_COMBUSTION_ENGINE_STATUS_FLAG_MISFIRE_SUPPORTED 8192
#define INTERNAL_COMBUSTION_ENGINE_STATUS_FLAG_MISFIRE_OBSERVED 16384
#define INTERNAL_COMBUSTION_ENGINE_STATUS_FLAG_OIL_PRESSURE_SUPPORTED 32768
#define INTERNAL_COMBUSTION_ENGINE_STATUS_FLAG_OIL_PRESSURE_BELOW_NOMINAL 65536
#define INTERNAL_COMBUSTION_ENGINE_STATUS_FLAG_OIL_PRESSURE_ABOVE_NOMINAL 131072
#define INTERNAL_COMBUSTION_ENGINE_STATUS_FLAG_DEBRIS_SUPPORTED 262144
#define INTERNAL_COMBUSTION_ENGINE_STATUS_FLAG_DEBRIS_DETECTED 524288
#define INTERNAL_COMBUSTION_ENGINE_STATUS_SPARK_PLUG_SINGLE 0
#define INTERNAL_COMBUSTION_ENGINE_STATUS_SPARK_PLUG_FIRST_ACTIVE 1
#define INTERNAL_COMBUSTION_ENGINE_STATUS_SPARK_PLUG_SECOND_ACTIVE 2
#define INTERNAL_COMBUSTION_ENGINE_STATUS_SPARK_PLUG_BOTH_ACTIVE 3

#endif


#ifdef __cplusplus
struct __EXPORT internal_combustion_engine_status_s {
#else
struct internal_combustion_engine_status_s {
#endif
	uint64_t timestamp;
	uint32_t flags;
	uint32_t engine_speed_rpm;
	float spark_dwell_time_ms;
	float atmospheric_pressure_kpa;
	float intake_manifold_pressure_kpa;
	float intake_manifold_temperature;
	float coolant_temperature;
	float oil_pressure;
	float oil_temperature;
	float fuel_pressure;
	float fuel_consumption_rate_cm3pm;
	float estimated_consumed_fuel_volume_cm3;
	float ignition_timing_deg;
	float injection_time_ms;
	float cylinder_head_temperature;
	float exhaust_gas_temperature;
	float lambda_coefficient;
	uint8_t state;
	uint8_t engine_load_percent;
	uint8_t throttle_position_percent;
	uint8_t ecu_index;
	uint8_t spark_plug_usage;
	uint8_t _padding0[7]; // required for logger


#ifdef __cplusplus
	static constexpr uint8_t STATE_STOPPED = 0;
	static constexpr uint8_t STATE_STARTING = 1;
	static constexpr uint8_t STATE_RUNNING = 2;
	static constexpr uint8_t STATE_FAULT = 3;
	static constexpr uint32_t FLAG_GENERAL_ERROR = 1;
	static constexpr uint32_t FLAG_CRANKSHAFT_SENSOR_ERROR_SUPPORTED = 2;
	static constexpr uint32_t FLAG_CRANKSHAFT_SENSOR_ERROR = 4;
	static constexpr uint32_t FLAG_TEMPERATURE_SUPPORTED = 8;
	static constexpr uint32_t FLAG_TEMPERATURE_BELOW_NOMINAL = 16;
	static constexpr uint32_t FLAG_TEMPERATURE_ABOVE_NOMINAL = 32;
	static constexpr uint32_t FLAG_TEMPERATURE_OVERHEATING = 64;
	static constexpr uint32_t FLAG_TEMPERATURE_EGT_ABOVE_NOMINAL = 128;
	static constexpr uint32_t FLAG_FUEL_PRESSURE_SUPPORTED = 256;
	static constexpr uint32_t FLAG_FUEL_PRESSURE_BELOW_NOMINAL = 512;
	static constexpr uint32_t FLAG_FUEL_PRESSURE_ABOVE_NOMINAL = 1024;
	static constexpr uint32_t FLAG_DETONATION_SUPPORTED = 2048;
	static constexpr uint32_t FLAG_DETONATION_OBSERVED = 4096;
	static constexpr uint32_t FLAG_MISFIRE_SUPPORTED = 8192;
	static constexpr uint32_t FLAG_MISFIRE_OBSERVED = 16384;
	static constexpr uint32_t FLAG_OIL_PRESSURE_SUPPORTED = 32768;
	static constexpr uint32_t FLAG_OIL_PRESSURE_BELOW_NOMINAL = 65536;
	static constexpr uint32_t FLAG_OIL_PRESSURE_ABOVE_NOMINAL = 131072;
	static constexpr uint32_t FLAG_DEBRIS_SUPPORTED = 262144;
	static constexpr uint32_t FLAG_DEBRIS_DETECTED = 524288;
	static constexpr uint8_t SPARK_PLUG_SINGLE = 0;
	static constexpr uint8_t SPARK_PLUG_FIRST_ACTIVE = 1;
	static constexpr uint8_t SPARK_PLUG_SECOND_ACTIVE = 2;
	static constexpr uint8_t SPARK_PLUG_BOTH_ACTIVE = 3;

#endif
};

#ifdef __cplusplus
namespace nextpilot {
	namespace msg {
		using InternalCombustionEngineStatus = internal_combustion_engine_status_s;
	} // namespace msg
} // namespace nextpilot
#endif

/* register this as object request broker structure */
ORB_DECLARE(internal_combustion_engine_status);


#ifdef __cplusplus
void print_message(const orb_metadata *meta, const internal_combustion_engine_status_s& message);
#endif
