
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file InternalCombustionEngineStatus.msg */


#include <rtdbg.h>
#include <inttypes.h>
#include <hrtimer.h>
#include <topics/uORBTopics.hpp>
#include <topics/internal_combustion_engine_status.h>

constexpr char __orb_internal_combustion_engine_status_fields[] = "\x89 timestamp;\x88 flags;\x88 engine_speed_rpm;\x8a spark_dwell_time_ms;\x8a atmospheric_pressure_kpa;\x8a intake_manifold_pressure_kpa;\x8a intake_manifold_temperature;\x8a coolant_temperature;\x8a oil_pressure;\x8a oil_temperature;\x8a fuel_pressure;\x8a fuel_consumption_rate_cm3pm;\x8a estimated_consumed_fuel_volume_cm3;\x8a ignition_timing_deg;\x8a injection_time_ms;\x8a cylinder_head_temperature;\x8a exhaust_gas_temperature;\x8a lambda_coefficient;\x86 state;\x86 engine_load_percent;\x86 throttle_position_percent;\x86 ecu_index;\x86 spark_plug_usage;\x86[7] _padding0;";

ORB_DEFINE(internal_combustion_engine_status, struct internal_combustion_engine_status_s, 81, __orb_internal_combustion_engine_status_fields, static_cast<uint8_t>(ORB_ID::internal_combustion_engine_status));


void print_message(const orb_metadata *meta, const internal_combustion_engine_status_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
