
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file D:\nextpilot\nextpilot-flight-control-public\msgs\uorb_msgs\IridiumsbdStatus.msg */


#include <rtdbg.h>
#include <inttypes.h>
//#include <px4_platform_common/log.h>
//#include <px4_platform_common/defines.h>
#include <topics/iridiumsbd_status.h>
#include <topics/uORBTopics.hpp>
#include <hrtimer.h>
//#include <lib/drivers/device/Device.hpp>
//#include <lib/matrix/matrix/math.hpp>
//#include <lib/mathlib/mathlib.h>

constexpr char __orb_iridiumsbd_status_fields[] = "\x89 timestamp;\x89 last_heartbeat;\x87 tx_buf_write_index;\x87 rx_buf_read_index;\x87 rx_buf_end_index;\x87 failed_sbd_sessions;\x87 successful_sbd_sessions;\x87 num_tx_buf_reset;\x86 signal_quality;\x86 state;\x8c ring_pending;\x8c tx_buf_write_pending;\x8c tx_session_pending;\x8c rx_read_pending;\x8c rx_session_pending;\x86[5] _padding0;";

ORB_DEFINE(iridiumsbd_status, struct iridiumsbd_status_s, 35, __orb_iridiumsbd_status_fields, static_cast<uint8_t>(ORB_ID::iridiumsbd_status));


void print_message(const orb_metadata *meta, const iridiumsbd_status_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
