
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file LandingTargetPose.msg */

#pragma once

#include <uORB.h>

#ifndef __cplusplus
#endif // __cplusplus


#ifdef __cplusplus
struct __EXPORT landing_target_pose_s {
#else
struct landing_target_pose_s {
#endif // __cplusplus
	uint64_t timestamp;
	float x_rel;
	float y_rel;
	float z_rel;
	float vx_rel;
	float vy_rel;
	float cov_x_rel;
	float cov_y_rel;
	float cov_vx_rel;
	float cov_vy_rel;
	float x_abs;
	float y_abs;
	float z_abs;
	bool is_static;
	bool rel_pos_valid;
	bool rel_vel_valid;
	bool abs_pos_valid;
	uint8_t _padding0[4]; // required for logger

#ifdef __cplusplus
#endif // __cplusplus
};

#ifdef __cplusplus
namespace nextpilot {
	namespace msg {
		using LandingTargetPose = landing_target_pose_s;
	} // namespace msg
} // namespace nextpilot
#endif // __cplusplus

/* register this as object request broker structure */
ORB_DECLARE(landing_target_pose);

#ifdef __cplusplus
void print_message(const orb_metadata *meta, const landing_target_pose_s& message);
#endif // __cplusplus
