
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file LandingGear.msg */

#pragma once

#include <uORB.h>

#ifndef __cplusplus
#define LANDING_GEAR_GEAR_UP 1
#define LANDING_GEAR_GEAR_DOWN -1
#define LANDING_GEAR_GEAR_KEEP 0
#endif // __cplusplus


#ifdef __cplusplus
struct __EXPORT landing_gear_s {
#else
struct landing_gear_s {
#endif // __cplusplus
	uint64_t timestamp;
	int8_t landing_gear;
	uint8_t _padding0[7]; // required for logger

#ifdef __cplusplus
	static constexpr int8_t GEAR_UP = 1;
	static constexpr int8_t GEAR_DOWN = -1;
	static constexpr int8_t GEAR_KEEP = 0;
#endif // __cplusplus
};

#ifdef __cplusplus
namespace nextpilot {
	namespace msg {
		using LandingGear = landing_gear_s;
	} // namespace msg
} // namespace nextpilot
#endif // __cplusplus

/* register this as object request broker structure */
ORB_DECLARE(landing_gear);

#ifdef __cplusplus
void print_message(const orb_metadata *meta, const landing_gear_s& message);
#endif // __cplusplus
