
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file LaunchDetectionStatus.msg */


#pragma once


#include <uORB.h>


#ifndef __cplusplus
#define LAUNCH_DETECTION_STATUS_STATE_WAITING_FOR_LAUNCH 0
#define LAUNCH_DETECTION_STATUS_STATE_LAUNCH_DETECTED_DISABLED_MOTOR 1
#define LAUNCH_DETECTION_STATUS_STATE_FLYING 2

#endif


#ifdef __cplusplus
struct __EXPORT launch_detection_status_s {
#else
struct launch_detection_status_s {
#endif
	uint64_t timestamp;
	uint8_t launch_detection_state;
	uint8_t _padding0[7]; // required for logger


#ifdef __cplusplus
	static constexpr uint8_t STATE_WAITING_FOR_LAUNCH = 0;
	static constexpr uint8_t STATE_LAUNCH_DETECTED_DISABLED_MOTOR = 1;
	static constexpr uint8_t STATE_FLYING = 2;

#endif
};

#ifdef __cplusplus
namespace nextpilot {
	namespace msg {
		using LaunchDetectionStatus = launch_detection_status_s;
	} // namespace msg
} // namespace nextpilot
#endif

/* register this as object request broker structure */
ORB_DECLARE(launch_detection_status);


#ifdef __cplusplus
void print_message(const orb_metadata *meta, const launch_detection_status_s& message);
#endif
