
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file D:\nextpilot\nextpilot-flight-control-public\msgs\uorb_msgs\MagnetometerBiasEstimate.msg */


#pragma once


#include <uORB.h>


#ifndef __cplusplus

#endif


#ifdef __cplusplus
struct __EXPORT magnetometer_bias_estimate_s {
#else
struct magnetometer_bias_estimate_s {
#endif
	uint64_t timestamp;
	float bias_x[4];
	float bias_y[4];
	float bias_z[4];
	bool valid[4];
	bool stable[4];


#ifdef __cplusplus

#endif
};

#ifdef __cplusplus
namespace nextpilot {
	namespace msg {
		using MagnetometerBiasEstimate = magnetometer_bias_estimate_s;
	} // namespace msg
} // namespace nextpilot
#endif

/* register this as object request broker structure */
ORB_DECLARE(magnetometer_bias_estimate);


#ifdef __cplusplus
void print_message(const orb_metadata *meta, const magnetometer_bias_estimate_s& message);
#endif
