
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file D:\nextpilot\nextpilot-flight-control-public\msgs\uorb_msgs\ManualControlSwitches.msg */


#include <rtdbg.h>
#include <inttypes.h>
//#include <px4_platform_common/log.h>
//#include <px4_platform_common/defines.h>
#include <topics/manual_control_switches.h>
#include <topics/uORBTopics.hpp>
#include <hrtimer.h>
//#include <lib/drivers/device/Device.hpp>
//#include <lib/matrix/matrix/math.hpp>
//#include <lib/mathlib/mathlib.h>

constexpr char __orb_manual_control_switches_fields[] = "\x89 timestamp;\x89 timestamp_sample;\x88 switch_changes;\x86 mode_slot;\x86 arm_switch;\x86 return_switch;\x86 loiter_switch;\x86 offboard_switch;\x86 kill_switch;\x86 gear_switch;\x86 transition_switch;\x86 photo_switch;\x86 video_switch;\x86 engage_main_motor_switch;\x86[1] _padding0;";

ORB_DEFINE(manual_control_switches, struct manual_control_switches_s, 31, __orb_manual_control_switches_fields, static_cast<uint8_t>(ORB_ID::manual_control_switches));


void print_message(const orb_metadata *meta, const manual_control_switches_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
