
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file ManualControlSetpoint.msg */


#include <rtdbg.h>
#include <inttypes.h>
#include <hrtimer.h>
#include <topics/uORBTopics.hpp>
#include <topics/manual_control_setpoint.h>

constexpr char __orb_manual_control_setpoint_fields[] = "\x89 timestamp;\x89 timestamp_sample;\x8a roll;\x8a pitch;\x8a yaw;\x8a throttle;\x8a flaps;\x8a aux1;\x8a aux2;\x8a aux3;\x8a aux4;\x8a aux5;\x8a aux6;\x8c valid;\x86 data_source;\x8c sticks_moving;\x86[1] _padding0;";

ORB_DEFINE(manual_control_setpoint, struct manual_control_setpoint_s, 63, __orb_manual_control_setpoint_fields, static_cast<uint8_t>(ORB_ID::manual_control_setpoint));
ORB_DEFINE(manual_control_input, struct manual_control_setpoint_s, 63, __orb_manual_control_setpoint_fields, static_cast<uint8_t>(ORB_ID::manual_control_input));


void print_message(const orb_metadata *meta, const manual_control_setpoint_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
