
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file MavlinkTunnel.msg */


#include <rtdbg.h>
#include <inttypes.h>
#include <hrtimer.h>
#include <topics/uORBTopics.hpp>
#include <topics/mavlink_tunnel.h>

constexpr char __orb_mavlink_tunnel_fields[] = "\x89 timestamp;\x87 payload_type;\x86 target_system;\x86 target_component;\x86 payload_length;\x86[128] payload;\x86[3] _padding0;";

ORB_DEFINE(mavlink_tunnel, struct mavlink_tunnel_s, 141, __orb_mavlink_tunnel_fields, static_cast<uint8_t>(ORB_ID::mavlink_tunnel));


void print_message(const orb_metadata *meta, const mavlink_tunnel_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
