
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file D:\nextpilot\nextpilot-flight-control-public\msgs\uorb_msgs\MavlinkTunnel.msg */


#pragma once


#include <uORB.h>


#ifndef __cplusplus
#define MAVLINK_TUNNEL_MAV_TUNNEL_PAYLOAD_TYPE_UNKNOWN 0
#define MAVLINK_TUNNEL_MAV_TUNNEL_PAYLOAD_TYPE_STORM32_RESERVED0 200
#define MAVLINK_TUNNEL_MAV_TUNNEL_PAYLOAD_TYPE_STORM32_RESERVED1 201
#define MAVLINK_TUNNEL_MAV_TUNNEL_PAYLOAD_TYPE_STORM32_RESERVED2 202
#define MAVLINK_TUNNEL_MAV_TUNNEL_PAYLOAD_TYPE_STORM32_RESERVED3 203
#define MAVLINK_TUNNEL_MAV_TUNNEL_PAYLOAD_TYPE_STORM32_RESERVED4 204
#define MAVLINK_TUNNEL_MAV_TUNNEL_PAYLOAD_TYPE_STORM32_RESERVED5 205
#define MAVLINK_TUNNEL_MAV_TUNNEL_PAYLOAD_TYPE_STORM32_RESERVED6 206
#define MAVLINK_TUNNEL_MAV_TUNNEL_PAYLOAD_TYPE_STORM32_RESERVED7 207
#define MAVLINK_TUNNEL_MAV_TUNNEL_PAYLOAD_TYPE_STORM32_RESERVED8 208
#define MAVLINK_TUNNEL_MAV_TUNNEL_PAYLOAD_TYPE_STORM32_RESERVED9 209

#endif


#ifdef __cplusplus
struct __EXPORT mavlink_tunnel_s {
#else
struct mavlink_tunnel_s {
#endif
	uint64_t timestamp;
	uint16_t payload_type;
	uint8_t target_system;
	uint8_t target_component;
	uint8_t payload_length;
	uint8_t payload[128];
	uint8_t _padding0[3]; // required for logger


#ifdef __cplusplus
	static constexpr uint8_t MAV_TUNNEL_PAYLOAD_TYPE_UNKNOWN = 0;
	static constexpr uint8_t MAV_TUNNEL_PAYLOAD_TYPE_STORM32_RESERVED0 = 200;
	static constexpr uint8_t MAV_TUNNEL_PAYLOAD_TYPE_STORM32_RESERVED1 = 201;
	static constexpr uint8_t MAV_TUNNEL_PAYLOAD_TYPE_STORM32_RESERVED2 = 202;
	static constexpr uint8_t MAV_TUNNEL_PAYLOAD_TYPE_STORM32_RESERVED3 = 203;
	static constexpr uint8_t MAV_TUNNEL_PAYLOAD_TYPE_STORM32_RESERVED4 = 204;
	static constexpr uint8_t MAV_TUNNEL_PAYLOAD_TYPE_STORM32_RESERVED5 = 205;
	static constexpr uint8_t MAV_TUNNEL_PAYLOAD_TYPE_STORM32_RESERVED6 = 206;
	static constexpr uint8_t MAV_TUNNEL_PAYLOAD_TYPE_STORM32_RESERVED7 = 207;
	static constexpr uint8_t MAV_TUNNEL_PAYLOAD_TYPE_STORM32_RESERVED8 = 208;
	static constexpr uint8_t MAV_TUNNEL_PAYLOAD_TYPE_STORM32_RESERVED9 = 209;

#endif
};

#ifdef __cplusplus
namespace nextpilot {
	namespace msg {
		using MavlinkTunnel = mavlink_tunnel_s;
	} // namespace msg
} // namespace nextpilot
#endif

/* register this as object request broker structure */
ORB_DECLARE(mavlink_tunnel);


#ifdef __cplusplus
void print_message(const orb_metadata *meta, const mavlink_tunnel_s& message);
#endif
