
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file D:\nextpilot\nextpilot-flight-control-public\msgs\uorb_msgs\NpfgStatus.msg */


#include <rtdbg.h>
#include <inttypes.h>
//#include <px4_platform_common/log.h>
//#include <px4_platform_common/defines.h>
#include <topics/npfg_status.h>
#include <topics/uORBTopics.hpp>
#include <hrtimer.h>
//#include <lib/drivers/device/Device.hpp>
//#include <lib/matrix/matrix/math.hpp>
//#include <lib/mathlib/mathlib.h>

constexpr char __orb_npfg_status_fields[] = "\x89 timestamp;\x8a lat_accel;\x8a lat_accel_ff;\x8a bearing_feas;\x8a bearing_feas_on_track;\x8a signed_track_error;\x8a track_error_bound;\x8a airspeed_ref;\x8a bearing;\x8a heading_ref;\x8a min_ground_speed_ref;\x8a adapted_period;\x8a p_gain;\x8a time_const;\x86 wind_est_valid;\x86[3] _padding0;";

ORB_DEFINE(npfg_status, struct npfg_status_s, 61, __orb_npfg_status_fields, static_cast<uint8_t>(ORB_ID::npfg_status));


void print_message(const orb_metadata *meta, const npfg_status_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
