
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file ObstacleDistance.msg */

#pragma once

#include <uORB.h>

#ifndef __cplusplus
#define OBSTACLE_DISTANCE_MAV_FRAME_GLOBAL 0
#define OBSTACLE_DISTANCE_MAV_FRAME_LOCAL_NED 1
#define OBSTACLE_DISTANCE_MAV_FRAME_BODY_FRD 12
#define OBSTACLE_DISTANCE_MAV_DISTANCE_SENSOR_LASER 0
#define OBSTACLE_DISTANCE_MAV_DISTANCE_SENSOR_ULTRASOUND 1
#define OBSTACLE_DISTANCE_MAV_DISTANCE_SENSOR_INFRARED 2
#define OBSTACLE_DISTANCE_MAV_DISTANCE_SENSOR_RADAR 3
#endif // __cplusplus


#ifdef __cplusplus
struct __EXPORT obstacle_distance_s {
#else
struct obstacle_distance_s {
#endif // __cplusplus
	uint64_t timestamp;
	float increment;
	float angle_offset;
	uint16_t distances[72];
	uint16_t min_distance;
	uint16_t max_distance;
	uint8_t frame;
	uint8_t sensor_type;
	uint8_t _padding0[2]; // required for logger

#ifdef __cplusplus
	static constexpr uint8_t MAV_FRAME_GLOBAL = 0;
	static constexpr uint8_t MAV_FRAME_LOCAL_NED = 1;
	static constexpr uint8_t MAV_FRAME_BODY_FRD = 12;
	static constexpr uint8_t MAV_DISTANCE_SENSOR_LASER = 0;
	static constexpr uint8_t MAV_DISTANCE_SENSOR_ULTRASOUND = 1;
	static constexpr uint8_t MAV_DISTANCE_SENSOR_INFRARED = 2;
	static constexpr uint8_t MAV_DISTANCE_SENSOR_RADAR = 3;
#endif // __cplusplus
};

#ifdef __cplusplus
namespace nextpilot {
	namespace msg {
		using ObstacleDistance = obstacle_distance_s;
	} // namespace msg
} // namespace nextpilot
#endif // __cplusplus

/* register this as object request broker structure */
ORB_DECLARE(obstacle_distance);
ORB_DECLARE(obstacle_distance_fused);

#ifdef __cplusplus
void print_message(const orb_metadata *meta, const obstacle_distance_s& message);
#endif // __cplusplus
