
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file OffboardControlMode.msg */


#pragma once


#include <uORB.h>


#ifndef __cplusplus

#endif


#ifdef __cplusplus
struct __EXPORT offboard_control_mode_s {
#else
struct offboard_control_mode_s {
#endif
	uint64_t timestamp;
	bool position;
	bool velocity;
	bool acceleration;
	bool attitude;
	bool body_rate;
	bool actuator;
	uint8_t _padding0[2]; // required for logger


#ifdef __cplusplus

#endif
};

#ifdef __cplusplus
namespace nextpilot {
	namespace msg {
		using OffboardControlMode = offboard_control_mode_s;
	} // namespace msg
} // namespace nextpilot
#endif

/* register this as object request broker structure */
ORB_DECLARE(offboard_control_mode);


#ifdef __cplusplus
void print_message(const orb_metadata *meta, const offboard_control_mode_s& message);
#endif
