
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file OffboardControlMode.msg */


#include <rtdbg.h>
#include <inttypes.h>
#include <hrtimer.h>
#include <topics/uORBTopics.hpp>
#include <topics/offboard_control_mode.h>

constexpr char __orb_offboard_control_mode_fields[] = "\x89 timestamp;\x8c position;\x8c velocity;\x8c acceleration;\x8c attitude;\x8c body_rate;\x8c actuator;\x86[2] _padding0;";

ORB_DEFINE(offboard_control_mode, struct offboard_control_mode_s, 14, __orb_offboard_control_mode_fields, static_cast<uint8_t>(ORB_ID::offboard_control_mode));


void print_message(const orb_metadata *meta, const offboard_control_mode_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
