
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file D:\nextpilot\nextpilot-flight-control-public\msgs\uorb_msgs\OnboardComputerStatus.msg */


#pragma once


#include <uORB.h>


#ifndef __cplusplus

#endif


#ifdef __cplusplus
struct __EXPORT onboard_computer_status_s {
#else
struct onboard_computer_status_s {
#endif
	uint64_t timestamp;
	uint32_t uptime;
	uint32_t ram_usage;
	uint32_t ram_total;
	uint32_t storage_type[4];
	uint32_t storage_usage[4];
	uint32_t storage_total[4];
	uint32_t link_type[6];
	uint32_t link_tx_rate[6];
	uint32_t link_rx_rate[6];
	uint32_t link_tx_max[6];
	uint32_t link_rx_max[6];
	int16_t fan_speed[4];
	uint8_t type;
	uint8_t cpu_cores[8];
	uint8_t cpu_combined[10];
	uint8_t gpu_cores[4];
	uint8_t gpu_combined[10];
	int8_t temperature_board;
	int8_t temperature_core[8];
	uint8_t _padding0[2]; // required for logger


#ifdef __cplusplus

#endif
};

#ifdef __cplusplus
namespace nextpilot {
	namespace msg {
		using OnboardComputerStatus = onboard_computer_status_s;
	} // namespace msg
} // namespace nextpilot
#endif

/* register this as object request broker structure */
ORB_DECLARE(onboard_computer_status);


#ifdef __cplusplus
void print_message(const orb_metadata *meta, const onboard_computer_status_s& message);
#endif
