
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file OnboardComputerStatus.msg */


#include <rtdbg.h>
#include <inttypes.h>
#include <hrtimer.h>
#include <topics/uORBTopics.hpp>
#include <topics/onboard_computer_status.h>

constexpr char __orb_onboard_computer_status_fields[] = "\x89 timestamp;\x88 uptime;\x88 ram_usage;\x88 ram_total;\x88[4] storage_type;\x88[4] storage_usage;\x88[4] storage_total;\x88[6] link_type;\x88[6] link_tx_rate;\x88[6] link_rx_rate;\x88[6] link_tx_max;\x88[6] link_rx_max;\x83[4] fan_speed;\x86 type;\x86[8] cpu_cores;\x86[10] cpu_combined;\x86[4] gpu_cores;\x86[10] gpu_combined;\x82 temperature_board;\x82[8] temperature_core;\x86[2] _padding0;";

ORB_DEFINE(onboard_computer_status, struct onboard_computer_status_s, 238, __orb_onboard_computer_status_fields, static_cast<uint8_t>(ORB_ID::onboard_computer_status));


void print_message(const orb_metadata *meta, const onboard_computer_status_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
