
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file ParameterUpdate.msg */


#include <rtdbg.h>
#include <inttypes.h>
#include <hrtimer.h>
#include <topics/uORBTopics.hpp>
#include <topics/parameter_update.h>

constexpr char __orb_parameter_update_fields[] = "\x89 timestamp;\x88 instance;\x88 get_count;\x88 set_count;\x88 find_count;\x88 export_count;\x87 active;\x87 changed;\x87 custom_default;\x86[6] _padding0;";

ORB_DEFINE(parameter_update, struct parameter_update_s, 34, __orb_parameter_update_fields, static_cast<uint8_t>(ORB_ID::parameter_update));


void print_message(const orb_metadata *meta, const parameter_update_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
