
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file D:\nextpilot\nextpilot-flight-control-public\msgs\uorb_msgs\Ping.msg */


#include <rtdbg.h>
#include <inttypes.h>
//#include <px4_platform_common/log.h>
//#include <px4_platform_common/defines.h>
#include <topics/ping.h>
#include <topics/uORBTopics.hpp>
#include <hrtimer.h>
//#include <lib/drivers/device/Device.hpp>
//#include <lib/matrix/matrix/math.hpp>
//#include <lib/mathlib/mathlib.h>

constexpr char __orb_ping_fields[] = "\x89 timestamp;\x89 ping_time;\x88 ping_sequence;\x88 dropped_packets;\x8a rtt_ms;\x86 system_id;\x86 component_id;\x86[2] _padding0;";

ORB_DEFINE(ping, struct ping_s, 30, __orb_ping_fields, static_cast<uint8_t>(ORB_ID::ping));


void print_message(const orb_metadata *meta, const ping_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
