
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file D:\nextpilot\nextpilot-flight-control-public\msgs\uorb_msgs\PositionControllerLandingStatus.msg */


#pragma once


#include <uORB.h>


#ifndef __cplusplus
#define POSITION_CONTROLLER_LANDING_STATUS_NOT_ABORTED 0
#define POSITION_CONTROLLER_LANDING_STATUS_ABORTED_BY_OPERATOR 1
#define POSITION_CONTROLLER_LANDING_STATUS_TERRAIN_NOT_FOUND 2
#define POSITION_CONTROLLER_LANDING_STATUS_TERRAIN_TIMEOUT 3
#define POSITION_CONTROLLER_LANDING_STATUS_UNKNOWN_ABORT_CRITERION 4

#endif


#ifdef __cplusplus
struct __EXPORT position_controller_landing_status_s {
#else
struct position_controller_landing_status_s {
#endif
	uint64_t timestamp;
	float lateral_touchdown_offset;
	bool flaring;
	uint8_t abort_status;
	uint8_t _padding0[2]; // required for logger


#ifdef __cplusplus
	static constexpr uint8_t NOT_ABORTED = 0;
	static constexpr uint8_t ABORTED_BY_OPERATOR = 1;
	static constexpr uint8_t TERRAIN_NOT_FOUND = 2;
	static constexpr uint8_t TERRAIN_TIMEOUT = 3;
	static constexpr uint8_t UNKNOWN_ABORT_CRITERION = 4;

#endif
};

#ifdef __cplusplus
namespace nextpilot {
	namespace msg {
		using PositionControllerLandingStatus = position_controller_landing_status_s;
	} // namespace msg
} // namespace nextpilot
#endif

/* register this as object request broker structure */
ORB_DECLARE(position_controller_landing_status);


#ifdef __cplusplus
void print_message(const orb_metadata *meta, const position_controller_landing_status_s& message);
#endif
