
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file D:\nextpilot\nextpilot-flight-control-public\msgs\uorb_msgs\PositionSetpoint.msg */


#include <rtdbg.h>
#include <inttypes.h>
//#include <px4_platform_common/log.h>
//#include <px4_platform_common/defines.h>
#include <topics/position_setpoint.h>
#include <topics/uORBTopics.hpp>
#include <hrtimer.h>
//#include <lib/drivers/device/Device.hpp>
//#include <lib/matrix/matrix/math.hpp>
//#include <lib/mathlib/mathlib.h>

constexpr char __orb_position_setpoint_fields[] = "\x89 timestamp;\x8b lat;\x8b lon;\x8a vx;\x8a vy;\x8a vz;\x8a alt;\x8a yaw;\x8a yawspeed;\x8a loiter_radius;\x8a acceptance_radius;\x8a cruising_speed;\x8a cruising_throttle;\x8c valid;\x86 type;\x8c yaw_valid;\x8c yawspeed_valid;\x8c loiter_direction_counter_clockwise;\x8c gliding_enabled;\x8c disable_weather_vane;\x86[1] _padding0;";

ORB_DEFINE(position_setpoint, struct position_setpoint_s, 71, __orb_position_setpoint_fields, static_cast<uint8_t>(ORB_ID::position_setpoint));


void print_message(const orb_metadata *meta, const position_setpoint_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
