
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file PositionSetpointTriplet.msg */


#include <rtdbg.h>
#include <inttypes.h>
#include <hrtimer.h>
#include <topics/uORBTopics.hpp>
#include <topics/position_setpoint_triplet.h>

constexpr char __orb_position_setpoint_triplet_fields[] = "\x89 timestamp;position_setpoint previous;position_setpoint current;position_setpoint next;";

ORB_DEFINE(position_setpoint_triplet, struct position_setpoint_triplet_s, 224, __orb_position_setpoint_triplet_fields, static_cast<uint8_t>(ORB_ID::position_setpoint_triplet));


void print_message(const orb_metadata *meta, const position_setpoint_triplet_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
