
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file PositionControllerStatus.msg */


#pragma once


#include <uORB.h>


#ifndef __cplusplus

#endif


#ifdef __cplusplus
struct __EXPORT position_controller_status_s {
#else
struct position_controller_status_s {
#endif
	uint64_t timestamp;
	float nav_roll;
	float nav_pitch;
	float nav_bearing;
	float target_bearing;
	float xtrack_error;
	float wp_dist;
	float acceptance_radius;
	float yaw_acceptance;
	float altitude_acceptance;
	uint8_t type;
	uint8_t _padding0[3]; // required for logger


#ifdef __cplusplus

#endif
};

#ifdef __cplusplus
namespace nextpilot {
	namespace msg {
		using PositionControllerStatus = position_controller_status_s;
	} // namespace msg
} // namespace nextpilot
#endif

/* register this as object request broker structure */
ORB_DECLARE(position_controller_status);


#ifdef __cplusplus
void print_message(const orb_metadata *meta, const position_controller_status_s& message);
#endif
