
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file PowerButtonState.msg */

#pragma once

#include <uORB.h>

#ifndef __cplusplus
#define POWER_BUTTON_STATE_PWR_BUTTON_STATE_IDEL 0
#define POWER_BUTTON_STATE_PWR_BUTTON_STATE_DOWN 1
#define POWER_BUTTON_STATE_PWR_BUTTON_STATE_UP 2
#define POWER_BUTTON_STATE_PWR_BUTTON_STATE_REQUEST_SHUTDOWN 3
#endif // __cplusplus


#ifdef __cplusplus
struct __EXPORT power_button_state_s {
#else
struct power_button_state_s {
#endif // __cplusplus
	uint64_t timestamp;
	uint8_t event;
	uint8_t _padding0[7]; // required for logger

#ifdef __cplusplus
	static constexpr uint8_t PWR_BUTTON_STATE_IDEL = 0;
	static constexpr uint8_t PWR_BUTTON_STATE_DOWN = 1;
	static constexpr uint8_t PWR_BUTTON_STATE_UP = 2;
	static constexpr uint8_t PWR_BUTTON_STATE_REQUEST_SHUTDOWN = 3;
#endif // __cplusplus
};

#ifdef __cplusplus
namespace nextpilot {
	namespace msg {
		using PowerButtonState = power_button_state_s;
	} // namespace msg
} // namespace nextpilot
#endif // __cplusplus

/* register this as object request broker structure */
ORB_DECLARE(power_button_state);

#ifdef __cplusplus
void print_message(const orb_metadata *meta, const power_button_state_s& message);
#endif // __cplusplus
