
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file PowerMonitor.msg */


#pragma once


#include <uORB.h>


#ifndef __cplusplus

#endif


#ifdef __cplusplus
struct __EXPORT power_monitor_s {
#else
struct power_monitor_s {
#endif
	uint64_t timestamp;
	float voltage_v;
	float current_a;
	float power_w;
	int16_t rconf;
	int16_t rsv;
	int16_t rbv;
	int16_t rp;
	int16_t rc;
	int16_t rcal;
	int16_t me;
	int16_t al;
	uint8_t _padding0[4]; // required for logger


#ifdef __cplusplus

#endif
};

#ifdef __cplusplus
namespace nextpilot {
	namespace msg {
		using PowerMonitor = power_monitor_s;
	} // namespace msg
} // namespace nextpilot
#endif

/* register this as object request broker structure */
ORB_DECLARE(power_monitor);


#ifdef __cplusplus
void print_message(const orb_metadata *meta, const power_monitor_s& message);
#endif
