
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file D:\nextpilot\nextpilot-flight-control-public\msgs\uorb_msgs\Px4ioStatus.msg */


#include <rtdbg.h>
#include <inttypes.h>
//#include <px4_platform_common/log.h>
//#include <px4_platform_common/defines.h>
#include <topics/px4io_status.h>
#include <topics/uORBTopics.hpp>
#include <hrtimer.h>
//#include <lib/drivers/device/Device.hpp>
//#include <lib/matrix/matrix/math.hpp>
//#include <lib/mathlib/mathlib.h>

constexpr char __orb_px4io_status_fields[] = "\x89 timestamp;\x8a voltage_v;\x8a rssi_v;\x87 free_memory_bytes;\x87[8] pwm;\x87[8] pwm_disarmed;\x87[8] pwm_failsafe;\x87[8] pwm_rate_hz;\x87[18] raw_inputs;\x8c status_arm_sync;\x8c status_failsafe;\x8c status_fmu_initialized;\x8c status_fmu_ok;\x8c status_init_ok;\x8c status_outputs_armed;\x8c status_raw_pwm;\x8c status_rc_ok;\x8c status_rc_dsm;\x8c status_rc_ppm;\x8c status_rc_sbus;\x8c status_rc_st24;\x8c status_rc_sumd;\x8c status_safety_button_event;\x8c alarm_pwm_error;\x8c alarm_rc_lost;\x8c arming_failsafe_custom;\x8c arming_fmu_armed;\x8c arming_fmu_prearmed;\x8c arming_force_failsafe;\x8c arming_io_arm_ok;\x8c arming_lockdown;\x8c arming_termination_failsafe;\x86[3] _padding0;";

ORB_DEFINE(px4io_status, struct px4io_status_s, 141, __orb_px4io_status_fields, static_cast<uint8_t>(ORB_ID::px4io_status));


void print_message(const orb_metadata *meta, const px4io_status_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
