
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file QshellReq.msg */


#include <rtdbg.h>
#include <inttypes.h>
#include <hrtimer.h>
#include <topics/uORBTopics.hpp>
#include <topics/qshell_req.h>

constexpr char __orb_qshell_req_fields[] = "\x89 timestamp;\x88 strlen;\x88 request_sequence;\x8d[100] cmd;\x86[4] _padding0;";

ORB_DEFINE(qshell_req, struct qshell_req_s, 116, __orb_qshell_req_fields, static_cast<uint8_t>(ORB_ID::qshell_req));


void print_message(const orb_metadata *meta, const qshell_req_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
