
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file D:\nextpilot\nextpilot-flight-control-public\msgs\uorb_msgs\RcChannels.msg */


#pragma once


#include <uORB.h>


#ifndef __cplusplus
#define RC_CHANNELS_FUNCTION_THROTTLE 0
#define RC_CHANNELS_FUNCTION_ROLL 1
#define RC_CHANNELS_FUNCTION_PITCH 2
#define RC_CHANNELS_FUNCTION_YAW 3
#define RC_CHANNELS_FUNCTION_RETURN 4
#define RC_CHANNELS_FUNCTION_LOITER 5
#define RC_CHANNELS_FUNCTION_OFFBOARD 6
#define RC_CHANNELS_FUNCTION_FLAPS 7
#define RC_CHANNELS_FUNCTION_AUX_1 8
#define RC_CHANNELS_FUNCTION_AUX_2 9
#define RC_CHANNELS_FUNCTION_AUX_3 10
#define RC_CHANNELS_FUNCTION_AUX_4 11
#define RC_CHANNELS_FUNCTION_AUX_5 12
#define RC_CHANNELS_FUNCTION_AUX_6 13
#define RC_CHANNELS_FUNCTION_PARAM_1 14
#define RC_CHANNELS_FUNCTION_PARAM_2 15
#define RC_CHANNELS_FUNCTION_PARAM_3_5 16
#define RC_CHANNELS_FUNCTION_KILLSWITCH 17
#define RC_CHANNELS_FUNCTION_TRANSITION 18
#define RC_CHANNELS_FUNCTION_GEAR 19
#define RC_CHANNELS_FUNCTION_ARMSWITCH 20
#define RC_CHANNELS_FUNCTION_FLTBTN_SLOT_1 21
#define RC_CHANNELS_FUNCTION_FLTBTN_SLOT_2 22
#define RC_CHANNELS_FUNCTION_FLTBTN_SLOT_3 23
#define RC_CHANNELS_FUNCTION_FLTBTN_SLOT_4 24
#define RC_CHANNELS_FUNCTION_FLTBTN_SLOT_5 25
#define RC_CHANNELS_FUNCTION_FLTBTN_SLOT_6 26
#define RC_CHANNELS_FUNCTION_ENGAGE_MAIN_MOTOR 27
#define RC_CHANNELS_FUNCTION_FLTBTN_SLOT_COUNT 6

#endif


#ifdef __cplusplus
struct __EXPORT rc_channels_s {
#else
struct rc_channels_s {
#endif
	uint64_t timestamp;
	uint64_t timestamp_last_valid;
	float channels[18];
	uint32_t frame_drop_count;
	uint8_t channel_count;
	int8_t function[28];
	uint8_t rssi;
	bool signal_lost;
	uint8_t _padding0[5]; // required for logger


#ifdef __cplusplus
	static constexpr uint8_t FUNCTION_THROTTLE = 0;
	static constexpr uint8_t FUNCTION_ROLL = 1;
	static constexpr uint8_t FUNCTION_PITCH = 2;
	static constexpr uint8_t FUNCTION_YAW = 3;
	static constexpr uint8_t FUNCTION_RETURN = 4;
	static constexpr uint8_t FUNCTION_LOITER = 5;
	static constexpr uint8_t FUNCTION_OFFBOARD = 6;
	static constexpr uint8_t FUNCTION_FLAPS = 7;
	static constexpr uint8_t FUNCTION_AUX_1 = 8;
	static constexpr uint8_t FUNCTION_AUX_2 = 9;
	static constexpr uint8_t FUNCTION_AUX_3 = 10;
	static constexpr uint8_t FUNCTION_AUX_4 = 11;
	static constexpr uint8_t FUNCTION_AUX_5 = 12;
	static constexpr uint8_t FUNCTION_AUX_6 = 13;
	static constexpr uint8_t FUNCTION_PARAM_1 = 14;
	static constexpr uint8_t FUNCTION_PARAM_2 = 15;
	static constexpr uint8_t FUNCTION_PARAM_3_5 = 16;
	static constexpr uint8_t FUNCTION_KILLSWITCH = 17;
	static constexpr uint8_t FUNCTION_TRANSITION = 18;
	static constexpr uint8_t FUNCTION_GEAR = 19;
	static constexpr uint8_t FUNCTION_ARMSWITCH = 20;
	static constexpr uint8_t FUNCTION_FLTBTN_SLOT_1 = 21;
	static constexpr uint8_t FUNCTION_FLTBTN_SLOT_2 = 22;
	static constexpr uint8_t FUNCTION_FLTBTN_SLOT_3 = 23;
	static constexpr uint8_t FUNCTION_FLTBTN_SLOT_4 = 24;
	static constexpr uint8_t FUNCTION_FLTBTN_SLOT_5 = 25;
	static constexpr uint8_t FUNCTION_FLTBTN_SLOT_6 = 26;
	static constexpr uint8_t FUNCTION_ENGAGE_MAIN_MOTOR = 27;
	static constexpr uint8_t FUNCTION_FLTBTN_SLOT_COUNT = 6;

#endif
};

#ifdef __cplusplus
namespace nextpilot {
	namespace msg {
		using RcChannels = rc_channels_s;
	} // namespace msg
} // namespace nextpilot
#endif

/* register this as object request broker structure */
ORB_DECLARE(rc_channels);


#ifdef __cplusplus
void print_message(const orb_metadata *meta, const rc_channels_s& message);
#endif
