
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file SatelliteInfo.msg */


#pragma once


#include <uORB.h>


#ifndef __cplusplus
#define SATELLITE_INFO_SAT_INFO_MAX_SATELLITES 20

#endif


#ifdef __cplusplus
struct __EXPORT satellite_info_s {
#else
struct satellite_info_s {
#endif
	uint64_t timestamp;
	uint8_t count;
	uint8_t svid[20];
	uint8_t used[20];
	uint8_t elevation[20];
	uint8_t azimuth[20];
	uint8_t snr[20];
	uint8_t prn[20];
	uint8_t _padding0[7]; // required for logger


#ifdef __cplusplus
	static constexpr uint8_t SAT_INFO_MAX_SATELLITES = 20;

#endif
};

#ifdef __cplusplus
namespace nextpilot {
	namespace msg {
		using SatelliteInfo = satellite_info_s;
	} // namespace msg
} // namespace nextpilot
#endif

/* register this as object request broker structure */
ORB_DECLARE(satellite_info);


#ifdef __cplusplus
void print_message(const orb_metadata *meta, const satellite_info_s& message);
#endif
