
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file SatelliteInfo.msg */


#include <rtdbg.h>
#include <inttypes.h>
#include <hrtimer.h>
#include <topics/uORBTopics.hpp>
#include <topics/satellite_info.h>

constexpr char __orb_satellite_info_fields[] = "\x89 timestamp;\x86 count;\x86[20] svid;\x86[20] used;\x86[20] elevation;\x86[20] azimuth;\x86[20] snr;\x86[20] prn;\x86[7] _padding0;";

ORB_DEFINE(satellite_info, struct satellite_info_s, 129, __orb_satellite_info_fields, static_cast<uint8_t>(ORB_ID::satellite_info));


void print_message(const orb_metadata *meta, const satellite_info_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
