
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file D:\nextpilot\nextpilot-flight-control-public\msgs\uorb_msgs\SensorsStatusImu.msg */


#include <rtdbg.h>
#include <inttypes.h>
//#include <px4_platform_common/log.h>
//#include <px4_platform_common/defines.h>
#include <topics/sensors_status_imu.h>
#include <topics/uORBTopics.hpp>
#include <hrtimer.h>
//#include <lib/drivers/device/Device.hpp>
//#include <lib/matrix/matrix/math.hpp>
//#include <lib/mathlib/mathlib.h>

constexpr char __orb_sensors_status_imu_fields[] = "\x89 timestamp;\x88 accel_device_id_primary;\x88[4] accel_device_ids;\x8a[4] accel_inconsistency_m_s_s;\x88 gyro_device_id_primary;\x88[4] gyro_device_ids;\x8a[4] gyro_inconsistency_rad_s;\x8c[4] accel_healthy;\x86[4] accel_priority;\x8c[4] gyro_healthy;\x86[4] gyro_priority;";

ORB_DEFINE(sensors_status_imu, struct sensors_status_imu_s, 96, __orb_sensors_status_imu_fields, static_cast<uint8_t>(ORB_ID::sensors_status_imu));


void print_message(const orb_metadata *meta, const sensors_status_imu_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
