
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file SensorUwb.msg */


#include <rtdbg.h>
#include <inttypes.h>
#include <hrtimer.h>
#include <topics/uORBTopics.hpp>
#include <topics/sensor_uwb.h>

constexpr char __orb_sensor_uwb_fields[] = "\x89 timestamp;\x88 sessionid;\x88 time_offset;\x88 counter;\x8a distance;\x8a aoa_azimuth_dev;\x8a aoa_elevation_dev;\x8a aoa_azimuth_resp;\x8a aoa_elevation_resp;\x8a offset_x;\x8a offset_y;\x8a offset_z;\x87 mac;\x87 mac_dest;\x87 status;\x86 nlos;\x86 aoa_azimuth_fom;\x86 aoa_elevation_fom;\x86 aoa_dest_azimuth_fom;\x86 aoa_dest_elevation_fom;\x86 orientation;";

ORB_DEFINE(sensor_uwb, struct sensor_uwb_s, 64, __orb_sensor_uwb_fields, static_cast<uint8_t>(ORB_ID::sensor_uwb));


void print_message(const orb_metadata *meta, const sensor_uwb_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
