
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file D:\nextpilot\nextpilot-flight-control-public\msgs\uorb_msgs\SensorGyro.msg */


#pragma once


#include <uORB.h>


#ifndef __cplusplus
#define SENSOR_GYRO_ORB_QUEUE_LENGTH 8

#endif


#ifdef __cplusplus
struct __EXPORT sensor_gyro_s {
#else
struct sensor_gyro_s {
#endif
	uint64_t timestamp;
	uint64_t timestamp_sample;
	uint32_t device_id;
	float x;
	float y;
	float z;
	float temperature;
	uint32_t error_count;
	uint8_t clip_counter[3];
	uint8_t samples;
	uint8_t _padding0[4]; // required for logger


#ifdef __cplusplus
	static constexpr uint8_t ORB_QUEUE_LENGTH = 8;

#endif
};

#ifdef __cplusplus
namespace nextpilot {
	namespace msg {
		using SensorGyro = sensor_gyro_s;
	} // namespace msg
} // namespace nextpilot
#endif

/* register this as object request broker structure */
ORB_DECLARE(sensor_gyro);


#ifdef __cplusplus
void print_message(const orb_metadata *meta, const sensor_gyro_s& message);
#endif
