
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file SensorCorrection.msg */


#include <rtdbg.h>
#include <inttypes.h>
#include <hrtimer.h>
#include <topics/uORBTopics.hpp>
#include <topics/sensor_correction.h>

constexpr char __orb_sensor_correction_fields[] = "\x89 timestamp;\x88[4] gyro_device_ids;\x8a[4] gyro_temperature;\x8a[3] gyro_offset_0;\x8a[3] gyro_offset_1;\x8a[3] gyro_offset_2;\x8a[3] gyro_offset_3;\x88[4] accel_device_ids;\x8a[4] accel_temperature;\x8a[3] accel_offset_0;\x8a[3] accel_offset_1;\x8a[3] accel_offset_2;\x8a[3] accel_offset_3;\x88[4] baro_device_ids;\x8a[4] baro_temperature;\x8a baro_offset_0;\x8a baro_offset_1;\x8a baro_offset_2;\x8a baro_offset_3;";

ORB_DEFINE(sensor_correction, struct sensor_correction_s, 216, __orb_sensor_correction_fields, static_cast<uint8_t>(ORB_ID::sensor_correction));


void print_message(const orb_metadata *meta, const sensor_correction_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
