
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file D:\nextpilot\nextpilot-flight-control-public\msgs\uorb_msgs\SystemPower.msg */


#include <rtdbg.h>
#include <inttypes.h>
//#include <px4_platform_common/log.h>
//#include <px4_platform_common/defines.h>
#include <topics/system_power.h>
#include <topics/uORBTopics.hpp>
#include <hrtimer.h>
//#include <lib/drivers/device/Device.hpp>
//#include <lib/matrix/matrix/math.hpp>
//#include <lib/mathlib/mathlib.h>

constexpr char __orb_system_power_fields[] = "\x89 timestamp;\x8a voltage5v_v;\x8a[4] sensors3v3;\x86 sensors3v3_valid;\x86 usb_connected;\x86 brick_valid;\x86 usb_valid;\x86 servo_valid;\x86 periph_5v_oc;\x86 hipower_5v_oc;\x86 comp_5v_valid;\x86 can1_gps1_5v_valid;\x86[3] _padding0;";

ORB_DEFINE(system_power, struct system_power_s, 37, __orb_system_power_fields, static_cast<uint8_t>(ORB_ID::system_power));


void print_message(const orb_metadata *meta, const system_power_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
