
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file D:\nextpilot\nextpilot-flight-control-public\msgs\uorb_msgs\TaskStackInfo.msg */


#pragma once


#include <uORB.h>


#ifndef __cplusplus
#define TASK_STACK_INFO_ORB_QUEUE_LENGTH 2

#endif


#ifdef __cplusplus
struct __EXPORT task_stack_info_s {
#else
struct task_stack_info_s {
#endif
	uint64_t timestamp;
	uint16_t stack_free;
	char task_name[24];
	uint8_t _padding0[6]; // required for logger


#ifdef __cplusplus
	static constexpr uint8_t ORB_QUEUE_LENGTH = 2;

#endif
};

#ifdef __cplusplus
namespace nextpilot {
	namespace msg {
		using TaskStackInfo = task_stack_info_s;
	} // namespace msg
} // namespace nextpilot
#endif

/* register this as object request broker structure */
ORB_DECLARE(task_stack_info);


#ifdef __cplusplus
void print_message(const orb_metadata *meta, const task_stack_info_s& message);
#endif
