
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file TecsStatus.msg */


#include <rtdbg.h>
#include <inttypes.h>
#include <hrtimer.h>
#include <topics/uORBTopics.hpp>
#include <topics/tecs_status.h>

constexpr char __orb_tecs_status_fields[] = "\x89 timestamp;\x8a altitude_sp;\x8a altitude_reference;\x8a height_rate_reference;\x8a height_rate_direct;\x8a height_rate_setpoint;\x8a height_rate;\x8a equivalent_airspeed_sp;\x8a true_airspeed_sp;\x8a true_airspeed_filtered;\x8a true_airspeed_derivative_sp;\x8a true_airspeed_derivative;\x8a true_airspeed_derivative_raw;\x8a total_energy_rate_sp;\x8a total_energy_rate;\x8a total_energy_balance_rate_sp;\x8a total_energy_balance_rate;\x8a throttle_integ;\x8a pitch_integ;\x8a throttle_sp;\x8a pitch_sp_rad;\x8a throttle_trim;\x86 mode;\x86[3] _padding0;";

ORB_DEFINE(tecs_status, struct tecs_status_s, 93, __orb_tecs_status_fields, static_cast<uint8_t>(ORB_ID::tecs_status));


void print_message(const orb_metadata *meta, const tecs_status_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
