
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file TimesyncStatus.msg */


#include <rtdbg.h>
#include <inttypes.h>
#include <hrtimer.h>
#include <topics/uORBTopics.hpp>
#include <topics/timesync_status.h>

constexpr char __orb_timesync_status_fields[] = "\x89 timestamp;\x89 remote_timestamp;\x85 observed_offset;\x85 estimated_offset;\x88 round_trip_time;\x86 source_protocol;\x86[3] _padding0;";

ORB_DEFINE(timesync_status, struct timesync_status_s, 37, __orb_timesync_status_fields, static_cast<uint8_t>(ORB_ID::timesync_status));


void print_message(const orb_metadata *meta, const timesync_status_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
