
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file UavcanParameterRequest.msg */


#include <rtdbg.h>
#include <inttypes.h>
#include <hrtimer.h>
#include <topics/uORBTopics.hpp>
#include <topics/uavcan_parameter_request.h>

constexpr char __orb_uavcan_parameter_request_fields[] = "\x89 timestamp;\x85 int_value;\x8a real_value;\x83 param_index;\x86 message_type;\x86 node_id;\x8d[17] param_id;\x86 param_type;\x86[6] _padding0;";

ORB_DEFINE(uavcan_parameter_request, struct uavcan_parameter_request_s, 42, __orb_uavcan_parameter_request_fields, static_cast<uint8_t>(ORB_ID::uavcan_parameter_request));


void print_message(const orb_metadata *meta, const uavcan_parameter_request_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
