
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file UavcanParameterValue.msg */

#pragma once

#include <uORB.h>

#ifndef __cplusplus
#endif // __cplusplus


#ifdef __cplusplus
struct __EXPORT uavcan_parameter_value_s {
#else
struct uavcan_parameter_value_s {
#endif // __cplusplus
	uint64_t timestamp;
	int64_t int_value;
	float real_value;
	int16_t param_index;
	uint16_t param_count;
	uint8_t node_id;
	char param_id[17];
	uint8_t param_type;
	uint8_t _padding0[5]; // required for logger

#ifdef __cplusplus
#endif // __cplusplus
};

#ifdef __cplusplus
namespace nextpilot {
	namespace msg {
		using UavcanParameterValue = uavcan_parameter_value_s;
	} // namespace msg
} // namespace nextpilot
#endif // __cplusplus

/* register this as object request broker structure */
ORB_DECLARE(uavcan_parameter_value);

#ifdef __cplusplus
void print_message(const orb_metadata *meta, const uavcan_parameter_value_s& message);
#endif // __cplusplus
