
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file D:\nextpilot\nextpilot-flight-control-public\msgs\uorb_msgs\UlogStream.msg */


#pragma once


#include <uORB.h>


#ifndef __cplusplus
#define ULOG_STREAM_FLAGS_NEED_ACK 1
#define ULOG_STREAM_ORB_QUEUE_LENGTH 16

#endif


#ifdef __cplusplus
struct __EXPORT ulog_stream_s {
#else
struct ulog_stream_s {
#endif
	uint64_t timestamp;
	uint16_t msg_sequence;
	uint8_t length;
	uint8_t first_message_offset;
	uint8_t flags;
	uint8_t data[249];
	uint8_t _padding0[2]; // required for logger


#ifdef __cplusplus
	static constexpr uint8_t FLAGS_NEED_ACK = 1;
	static constexpr uint8_t ORB_QUEUE_LENGTH = 16;

#endif
};

#ifdef __cplusplus
namespace nextpilot {
	namespace msg {
		using UlogStream = ulog_stream_s;
	} // namespace msg
} // namespace nextpilot
#endif

/* register this as object request broker structure */
ORB_DECLARE(ulog_stream);


#ifdef __cplusplus
void print_message(const orb_metadata *meta, const ulog_stream_s& message);
#endif
