
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file VehicleCommandAck.msg */


#include <rtdbg.h>
#include <inttypes.h>
#include <hrtimer.h>
#include <topics/uORBTopics.hpp>
#include <topics/vehicle_command_ack.h>

constexpr char __orb_vehicle_command_ack_fields[] = "\x89 timestamp;\x88 command;\x84 result_param2;\x86 result;\x86 result_param1;\x86 target_system;\x86 target_component;\x8c from_external;\x86[3] _padding0;";

ORB_DEFINE(vehicle_command_ack, struct vehicle_command_ack_s, 21, __orb_vehicle_command_ack_fields, static_cast<uint8_t>(ORB_ID::vehicle_command_ack));


void print_message(const orb_metadata *meta, const vehicle_command_ack_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
