
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file VehicleImu.msg */


#include <rtdbg.h>
#include <inttypes.h>
#include <hrtimer.h>
#include <topics/uORBTopics.hpp>
#include <topics/vehicle_imu.h>

constexpr char __orb_vehicle_imu_fields[] = "\x89 timestamp;\x89 timestamp_sample;\x88 accel_device_id;\x88 gyro_device_id;\x8a[3] delta_angle;\x8a[3] delta_velocity;\x87 delta_angle_dt;\x87 delta_velocity_dt;\x86 delta_angle_clipping;\x86 delta_velocity_clipping;\x86 accel_calibration_count;\x86 gyro_calibration_count;";

ORB_DEFINE(vehicle_imu, struct vehicle_imu_s, 56, __orb_vehicle_imu_fields, static_cast<uint8_t>(ORB_ID::vehicle_imu));


void print_message(const orb_metadata *meta, const vehicle_imu_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
