
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file D:\nextpilot\nextpilot-flight-control-public\msgs\uorb_msgs\VehicleOdometry.msg */


#include <rtdbg.h>
#include <inttypes.h>
//#include <px4_platform_common/log.h>
//#include <px4_platform_common/defines.h>
#include <topics/vehicle_odometry.h>
#include <topics/uORBTopics.hpp>
#include <hrtimer.h>
//#include <lib/drivers/device/Device.hpp>
//#include <lib/matrix/matrix/math.hpp>
//#include <lib/mathlib/mathlib.h>

constexpr char __orb_vehicle_odometry_fields[] = "\x89 timestamp;\x89 timestamp_sample;\x8a[3] position;\x8a[4] q;\x8a[3] velocity;\x8a[3] angular_velocity;\x8a[3] position_variance;\x8a[3] orientation_variance;\x8a[3] velocity_variance;\x86 pose_frame;\x86 velocity_frame;\x86 reset_counter;\x82 quality;\x86[4] _padding0;";

ORB_DEFINE(vehicle_odometry, struct vehicle_odometry_s, 108, __orb_vehicle_odometry_fields, static_cast<uint8_t>(ORB_ID::vehicle_odometry));
ORB_DEFINE(vehicle_mocap_odometry, struct vehicle_odometry_s, 108, __orb_vehicle_odometry_fields, static_cast<uint8_t>(ORB_ID::vehicle_mocap_odometry));
ORB_DEFINE(vehicle_visual_odometry, struct vehicle_odometry_s, 108, __orb_vehicle_odometry_fields, static_cast<uint8_t>(ORB_ID::vehicle_visual_odometry));
ORB_DEFINE(estimator_odometry, struct vehicle_odometry_s, 108, __orb_vehicle_odometry_fields, static_cast<uint8_t>(ORB_ID::estimator_odometry));


void print_message(const orb_metadata *meta, const vehicle_odometry_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
