
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file D:\nextpilot\nextpilot-flight-control-public\msgs\uorb_msgs\VehicleAttitude.msg */


#include <rtdbg.h>
#include <inttypes.h>
//#include <px4_platform_common/log.h>
//#include <px4_platform_common/defines.h>
#include <topics/vehicle_attitude.h>
#include <topics/uORBTopics.hpp>
#include <hrtimer.h>
//#include <lib/drivers/device/Device.hpp>
//#include <lib/matrix/matrix/math.hpp>
//#include <lib/mathlib/mathlib.h>

constexpr char __orb_vehicle_attitude_fields[] = "\x89 timestamp;\x89 timestamp_sample;\x8a[4] q;\x8a[4] delta_q_reset;\x86 quat_reset_counter;\x86[7] _padding0;";

ORB_DEFINE(vehicle_attitude, struct vehicle_attitude_s, 49, __orb_vehicle_attitude_fields, static_cast<uint8_t>(ORB_ID::vehicle_attitude));
ORB_DEFINE(vehicle_attitude_groundtruth, struct vehicle_attitude_s, 49, __orb_vehicle_attitude_fields, static_cast<uint8_t>(ORB_ID::vehicle_attitude_groundtruth));
ORB_DEFINE(external_ins_attitude, struct vehicle_attitude_s, 49, __orb_vehicle_attitude_fields, static_cast<uint8_t>(ORB_ID::external_ins_attitude));
ORB_DEFINE(estimator_attitude, struct vehicle_attitude_s, 49, __orb_vehicle_attitude_fields, static_cast<uint8_t>(ORB_ID::estimator_attitude));


void print_message(const orb_metadata *meta, const vehicle_attitude_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
