
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file VehicleControlMode.msg */


#pragma once


#include <uORB.h>


#ifndef __cplusplus

#endif


#ifdef __cplusplus
struct __EXPORT vehicle_control_mode_s {
#else
struct vehicle_control_mode_s {
#endif
	uint64_t timestamp;
	bool flag_armed;
	bool flag_multicopter_position_control_enabled;
	bool flag_control_manual_enabled;
	bool flag_control_auto_enabled;
	bool flag_control_offboard_enabled;
	bool flag_control_rates_enabled;
	bool flag_control_attitude_enabled;
	bool flag_control_acceleration_enabled;
	bool flag_control_velocity_enabled;
	bool flag_control_position_enabled;
	bool flag_control_altitude_enabled;
	bool flag_control_climb_rate_enabled;
	bool flag_control_termination_enabled;
	uint8_t _padding0[3]; // required for logger


#ifdef __cplusplus

#endif
};

#ifdef __cplusplus
namespace nextpilot {
	namespace msg {
		using VehicleControlMode = vehicle_control_mode_s;
	} // namespace msg
} // namespace nextpilot
#endif

/* register this as object request broker structure */
ORB_DECLARE(vehicle_control_mode);


#ifdef __cplusplus
void print_message(const orb_metadata *meta, const vehicle_control_mode_s& message);
#endif
