
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file VehicleOpticalFlowVel.msg */


#pragma once


#include <uORB.h>


#ifndef __cplusplus

#endif


#ifdef __cplusplus
struct __EXPORT vehicle_optical_flow_vel_s {
#else
struct vehicle_optical_flow_vel_s {
#endif
	uint64_t timestamp;
	uint64_t timestamp_sample;
	float vel_body[2];
	float vel_ne[2];
	float flow_uncompensated_integral[2];
	float flow_compensated_integral[2];
	float gyro_rate[3];
	float gyro_rate_integral[3];


#ifdef __cplusplus

#endif
};

#ifdef __cplusplus
namespace nextpilot {
	namespace msg {
		using VehicleOpticalFlowVel = vehicle_optical_flow_vel_s;
	} // namespace msg
} // namespace nextpilot
#endif

/* register this as object request broker structure */
ORB_DECLARE(estimator_optical_flow_vel);
ORB_DECLARE(vehicle_optical_flow_vel);


#ifdef __cplusplus
void print_message(const orb_metadata *meta, const vehicle_optical_flow_vel_s& message);
#endif
