
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file VehicleMagnetometer.msg */


#include <rtdbg.h>
#include <inttypes.h>
#include <hrtimer.h>
#include <topics/uORBTopics.hpp>
#include <topics/vehicle_magnetometer.h>

constexpr char __orb_vehicle_magnetometer_fields[] = "\x89 timestamp;\x89 timestamp_sample;\x88 device_id;\x8a[3] magnetometer_ga;\x86 calibration_count;\x86[7] _padding0;";

ORB_DEFINE(vehicle_magnetometer, struct vehicle_magnetometer_s, 33, __orb_vehicle_magnetometer_fields, static_cast<uint8_t>(ORB_ID::vehicle_magnetometer));


void print_message(const orb_metadata *meta, const vehicle_magnetometer_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
