
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file D:\nextpilot\nextpilot-flight-control-public\msgs\uorb_msgs\VehicleOpticalFlow.msg */


#include <rtdbg.h>
#include <inttypes.h>
//#include <px4_platform_common/log.h>
//#include <px4_platform_common/defines.h>
#include <topics/vehicle_optical_flow.h>
#include <topics/uORBTopics.hpp>
#include <hrtimer.h>
//#include <lib/drivers/device/Device.hpp>
//#include <lib/matrix/matrix/math.hpp>
//#include <lib/mathlib/mathlib.h>

constexpr char __orb_vehicle_optical_flow_fields[] = "\x89 timestamp;\x89 timestamp_sample;\x88 device_id;\x8a[2] pixel_flow;\x8a[3] delta_angle;\x8a distance_m;\x88 integration_timespan_us;\x8a max_flow_rate;\x8a min_ground_distance;\x8a max_ground_distance;\x86 quality;\x86[3] _padding0;";

ORB_DEFINE(vehicle_optical_flow, struct vehicle_optical_flow_s, 61, __orb_vehicle_optical_flow_fields, static_cast<uint8_t>(ORB_ID::vehicle_optical_flow));


void print_message(const orb_metadata *meta, const vehicle_optical_flow_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
