
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file VehicleStatus.msg */


#pragma once


#include <uORB.h>


#ifndef __cplusplus
#define VEHICLE_STATUS_ARMING_STATE_INIT 0
#define VEHICLE_STATUS_ARMING_STATE_STANDBY 1
#define VEHICLE_STATUS_ARMING_STATE_ARMED 2
#define VEHICLE_STATUS_ARMING_STATE_STANDBY_ERROR 3
#define VEHICLE_STATUS_ARMING_STATE_SHUTDOWN 4
#define VEHICLE_STATUS_ARMING_STATE_IN_AIR_RESTORE 5
#define VEHICLE_STATUS_ARMING_STATE_MAX 6
#define VEHICLE_STATUS_ARM_DISARM_REASON_TRANSITION_TO_STANDBY 0
#define VEHICLE_STATUS_ARM_DISARM_REASON_RC_STICK 1
#define VEHICLE_STATUS_ARM_DISARM_REASON_RC_SWITCH 2
#define VEHICLE_STATUS_ARM_DISARM_REASON_COMMAND_INTERNAL 3
#define VEHICLE_STATUS_ARM_DISARM_REASON_COMMAND_EXTERNAL 4
#define VEHICLE_STATUS_ARM_DISARM_REASON_MISSION_START 5
#define VEHICLE_STATUS_ARM_DISARM_REASON_SAFETY_BUTTON 6
#define VEHICLE_STATUS_ARM_DISARM_REASON_AUTO_DISARM_LAND 7
#define VEHICLE_STATUS_ARM_DISARM_REASON_AUTO_DISARM_PREFLIGHT 8
#define VEHICLE_STATUS_ARM_DISARM_REASON_KILL_SWITCH 9
#define VEHICLE_STATUS_ARM_DISARM_REASON_LOCKDOWN 10
#define VEHICLE_STATUS_ARM_DISARM_REASON_FAILURE_DETECTOR 11
#define VEHICLE_STATUS_ARM_DISARM_REASON_SHUTDOWN 12
#define VEHICLE_STATUS_ARM_DISARM_REASON_UNIT_TEST 13
#define VEHICLE_STATUS_NAVIGATION_STATE_MANUAL 0
#define VEHICLE_STATUS_NAVIGATION_STATE_ALTCTL 1
#define VEHICLE_STATUS_NAVIGATION_STATE_POSCTL 2
#define VEHICLE_STATUS_NAVIGATION_STATE_AUTO_MISSION 3
#define VEHICLE_STATUS_NAVIGATION_STATE_AUTO_LOITER 4
#define VEHICLE_STATUS_NAVIGATION_STATE_AUTO_RTL 5
#define VEHICLE_STATUS_NAVIGATION_STATE_UNUSED3 8
#define VEHICLE_STATUS_NAVIGATION_STATE_UNUSED 9
#define VEHICLE_STATUS_NAVIGATION_STATE_ACRO 10
#define VEHICLE_STATUS_NAVIGATION_STATE_UNUSED1 11
#define VEHICLE_STATUS_NAVIGATION_STATE_DESCEND 12
#define VEHICLE_STATUS_NAVIGATION_STATE_TERMINATION 13
#define VEHICLE_STATUS_NAVIGATION_STATE_OFFBOARD 14
#define VEHICLE_STATUS_NAVIGATION_STATE_STAB 15
#define VEHICLE_STATUS_NAVIGATION_STATE_UNUSED2 16
#define VEHICLE_STATUS_NAVIGATION_STATE_AUTO_TAKEOFF 17
#define VEHICLE_STATUS_NAVIGATION_STATE_AUTO_LAND 18
#define VEHICLE_STATUS_NAVIGATION_STATE_AUTO_FOLLOW_TARGET 19
#define VEHICLE_STATUS_NAVIGATION_STATE_AUTO_PRECLAND 20
#define VEHICLE_STATUS_NAVIGATION_STATE_ORBIT 21
#define VEHICLE_STATUS_NAVIGATION_STATE_AUTO_VTOL_TAKEOFF 22
#define VEHICLE_STATUS_NAVIGATION_STATE_MAX 23
#define VEHICLE_STATUS_FAILURE_NONE 0
#define VEHICLE_STATUS_FAILURE_ROLL 1
#define VEHICLE_STATUS_FAILURE_PITCH 2
#define VEHICLE_STATUS_FAILURE_ALT 4
#define VEHICLE_STATUS_FAILURE_EXT 8
#define VEHICLE_STATUS_FAILURE_ARM_ESC 16
#define VEHICLE_STATUS_FAILURE_BATTERY 32
#define VEHICLE_STATUS_FAILURE_IMBALANCED_PROP 64
#define VEHICLE_STATUS_FAILURE_MOTOR 128
#define VEHICLE_STATUS_HIL_STATE_OFF 0
#define VEHICLE_STATUS_HIL_STATE_ON 1
#define VEHICLE_STATUS_VEHICLE_TYPE_UNKNOWN 0
#define VEHICLE_STATUS_VEHICLE_TYPE_ROTARY_WING 1
#define VEHICLE_STATUS_VEHICLE_TYPE_FIXED_WING 2
#define VEHICLE_STATUS_VEHICLE_TYPE_ROVER 3
#define VEHICLE_STATUS_VEHICLE_TYPE_AIRSHIP 4

#endif


#ifdef __cplusplus
struct __EXPORT vehicle_status_s {
#else
struct vehicle_status_s {
#endif
	uint64_t timestamp;
	uint64_t armed_time;
	uint64_t takeoff_time;
	uint64_t nav_state_timestamp;
	uint16_t failure_detector_status;
	uint8_t arming_state;
	uint8_t latest_arming_reason;
	uint8_t latest_disarming_reason;
	uint8_t nav_state_user_intention;
	uint8_t nav_state;
	uint8_t hil_state;
	uint8_t vehicle_type;
	bool failsafe;
	bool failsafe_and_user_took_over;
	bool gcs_connection_lost;
	uint8_t gcs_connection_lost_counter;
	bool high_latency_data_link_lost;
	bool is_vtol;
	bool is_vtol_tailsitter;
	bool in_transition_mode;
	bool in_transition_to_fw;
	uint8_t system_type;
	uint8_t system_id;
	uint8_t component_id;
	bool safety_button_available;
	bool safety_off;
	bool power_input_valid;
	bool usb_connected;
	bool open_drone_id_system_present;
	bool open_drone_id_system_healthy;
	bool parachute_system_present;
	bool parachute_system_healthy;
	bool avoidance_system_required;
	bool avoidance_system_valid;
	bool rc_calibration_in_progress;
	bool calibration_enabled;
	bool pre_flight_checks_pass;
	uint8_t _padding0[6]; // required for logger


#ifdef __cplusplus
	static constexpr uint8_t ARMING_STATE_INIT = 0;
	static constexpr uint8_t ARMING_STATE_STANDBY = 1;
	static constexpr uint8_t ARMING_STATE_ARMED = 2;
	static constexpr uint8_t ARMING_STATE_STANDBY_ERROR = 3;
	static constexpr uint8_t ARMING_STATE_SHUTDOWN = 4;
	static constexpr uint8_t ARMING_STATE_IN_AIR_RESTORE = 5;
	static constexpr uint8_t ARMING_STATE_MAX = 6;
	static constexpr uint8_t ARM_DISARM_REASON_TRANSITION_TO_STANDBY = 0;
	static constexpr uint8_t ARM_DISARM_REASON_RC_STICK = 1;
	static constexpr uint8_t ARM_DISARM_REASON_RC_SWITCH = 2;
	static constexpr uint8_t ARM_DISARM_REASON_COMMAND_INTERNAL = 3;
	static constexpr uint8_t ARM_DISARM_REASON_COMMAND_EXTERNAL = 4;
	static constexpr uint8_t ARM_DISARM_REASON_MISSION_START = 5;
	static constexpr uint8_t ARM_DISARM_REASON_SAFETY_BUTTON = 6;
	static constexpr uint8_t ARM_DISARM_REASON_AUTO_DISARM_LAND = 7;
	static constexpr uint8_t ARM_DISARM_REASON_AUTO_DISARM_PREFLIGHT = 8;
	static constexpr uint8_t ARM_DISARM_REASON_KILL_SWITCH = 9;
	static constexpr uint8_t ARM_DISARM_REASON_LOCKDOWN = 10;
	static constexpr uint8_t ARM_DISARM_REASON_FAILURE_DETECTOR = 11;
	static constexpr uint8_t ARM_DISARM_REASON_SHUTDOWN = 12;
	static constexpr uint8_t ARM_DISARM_REASON_UNIT_TEST = 13;
	static constexpr uint8_t NAVIGATION_STATE_MANUAL = 0;
	static constexpr uint8_t NAVIGATION_STATE_ALTCTL = 1;
	static constexpr uint8_t NAVIGATION_STATE_POSCTL = 2;
	static constexpr uint8_t NAVIGATION_STATE_AUTO_MISSION = 3;
	static constexpr uint8_t NAVIGATION_STATE_AUTO_LOITER = 4;
	static constexpr uint8_t NAVIGATION_STATE_AUTO_RTL = 5;
	static constexpr uint8_t NAVIGATION_STATE_UNUSED3 = 8;
	static constexpr uint8_t NAVIGATION_STATE_UNUSED = 9;
	static constexpr uint8_t NAVIGATION_STATE_ACRO = 10;
	static constexpr uint8_t NAVIGATION_STATE_UNUSED1 = 11;
	static constexpr uint8_t NAVIGATION_STATE_DESCEND = 12;
	static constexpr uint8_t NAVIGATION_STATE_TERMINATION = 13;
	static constexpr uint8_t NAVIGATION_STATE_OFFBOARD = 14;
	static constexpr uint8_t NAVIGATION_STATE_STAB = 15;
	static constexpr uint8_t NAVIGATION_STATE_UNUSED2 = 16;
	static constexpr uint8_t NAVIGATION_STATE_AUTO_TAKEOFF = 17;
	static constexpr uint8_t NAVIGATION_STATE_AUTO_LAND = 18;
	static constexpr uint8_t NAVIGATION_STATE_AUTO_FOLLOW_TARGET = 19;
	static constexpr uint8_t NAVIGATION_STATE_AUTO_PRECLAND = 20;
	static constexpr uint8_t NAVIGATION_STATE_ORBIT = 21;
	static constexpr uint8_t NAVIGATION_STATE_AUTO_VTOL_TAKEOFF = 22;
	static constexpr uint8_t NAVIGATION_STATE_MAX = 23;
	static constexpr uint16_t FAILURE_NONE = 0;
	static constexpr uint16_t FAILURE_ROLL = 1;
	static constexpr uint16_t FAILURE_PITCH = 2;
	static constexpr uint16_t FAILURE_ALT = 4;
	static constexpr uint16_t FAILURE_EXT = 8;
	static constexpr uint16_t FAILURE_ARM_ESC = 16;
	static constexpr uint16_t FAILURE_BATTERY = 32;
	static constexpr uint16_t FAILURE_IMBALANCED_PROP = 64;
	static constexpr uint16_t FAILURE_MOTOR = 128;
	static constexpr uint8_t HIL_STATE_OFF = 0;
	static constexpr uint8_t HIL_STATE_ON = 1;
	static constexpr uint8_t VEHICLE_TYPE_UNKNOWN = 0;
	static constexpr uint8_t VEHICLE_TYPE_ROTARY_WING = 1;
	static constexpr uint8_t VEHICLE_TYPE_FIXED_WING = 2;
	static constexpr uint8_t VEHICLE_TYPE_ROVER = 3;
	static constexpr uint8_t VEHICLE_TYPE_AIRSHIP = 4;

#endif
};

#ifdef __cplusplus
namespace nextpilot {
	namespace msg {
		using VehicleStatus = vehicle_status_s;
	} // namespace msg
} // namespace nextpilot
#endif

/* register this as object request broker structure */
ORB_DECLARE(vehicle_status);


#ifdef __cplusplus
void print_message(const orb_metadata *meta, const vehicle_status_s& message);
#endif
