
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file VehicleLocalPositionSetpoint.msg */


#pragma once


#include <uORB.h>


#ifndef __cplusplus

#endif


#ifdef __cplusplus
struct __EXPORT vehicle_local_position_setpoint_s {
#else
struct vehicle_local_position_setpoint_s {
#endif
	uint64_t timestamp;
	float x;
	float y;
	float z;
	float vx;
	float vy;
	float vz;
	float acceleration[3];
	float thrust[3];
	float yaw;
	float yawspeed;


#ifdef __cplusplus

#endif
};

#ifdef __cplusplus
namespace nextpilot {
	namespace msg {
		using VehicleLocalPositionSetpoint = vehicle_local_position_setpoint_s;
	} // namespace msg
} // namespace nextpilot
#endif

/* register this as object request broker structure */
ORB_DECLARE(vehicle_local_position_setpoint);


#ifdef __cplusplus
void print_message(const orb_metadata *meta, const vehicle_local_position_setpoint_s& message);
#endif
