
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file VehicleLandDetected.msg */


#include <rtdbg.h>
#include <inttypes.h>
#include <hrtimer.h>
#include <topics/uORBTopics.hpp>
#include <topics/vehicle_land_detected.h>

constexpr char __orb_vehicle_land_detected_fields[] = "\x89 timestamp;\x8c freefall;\x8c ground_contact;\x8c maybe_landed;\x8c landed;\x8c in_ground_effect;\x8c in_descend;\x8c has_low_throttle;\x8c vertical_movement;\x8c horizontal_movement;\x8c rotational_movement;\x8c close_to_ground_or_skipped_check;\x8c at_rest;\x86[4] _padding0;";

ORB_DEFINE(vehicle_land_detected, struct vehicle_land_detected_s, 20, __orb_vehicle_land_detected_fields, static_cast<uint8_t>(ORB_ID::vehicle_land_detected));


void print_message(const orb_metadata *meta, const vehicle_land_detected_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
