
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file D:\nextpilot\nextpilot-flight-control-public\msgs\uorb_msgs\VehicleTorqueSetpoint.msg */


#pragma once


#include <uORB.h>


#ifndef __cplusplus

#endif


#ifdef __cplusplus
struct __EXPORT vehicle_torque_setpoint_s {
#else
struct vehicle_torque_setpoint_s {
#endif
	uint64_t timestamp;
	uint64_t timestamp_sample;
	float xyz[3];
	uint8_t _padding0[4]; // required for logger


#ifdef __cplusplus

#endif
};

#ifdef __cplusplus
namespace nextpilot {
	namespace msg {
		using VehicleTorqueSetpoint = vehicle_torque_setpoint_s;
	} // namespace msg
} // namespace nextpilot
#endif

/* register this as object request broker structure */
ORB_DECLARE(vehicle_torque_setpoint);
ORB_DECLARE(vehicle_torque_setpoint_virtual_fw);
ORB_DECLARE(vehicle_torque_setpoint_virtual_mc);


#ifdef __cplusplus
void print_message(const orb_metadata *meta, const vehicle_torque_setpoint_s& message);
#endif
