
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file D:\nextpilot\nextpilot-flight-control-public\msgs\uorb_msgs\VehicleGlobalPosition.msg */


#include <rtdbg.h>
#include <inttypes.h>
//#include <px4_platform_common/log.h>
//#include <px4_platform_common/defines.h>
#include <topics/vehicle_global_position.h>
#include <topics/uORBTopics.hpp>
#include <hrtimer.h>
//#include <lib/drivers/device/Device.hpp>
//#include <lib/matrix/matrix/math.hpp>
//#include <lib/mathlib/mathlib.h>

constexpr char __orb_vehicle_global_position_fields[] = "\x89 timestamp;\x89 timestamp_sample;\x8b lat;\x8b lon;\x8a alt;\x8a alt_ellipsoid;\x8a delta_alt;\x8a eph;\x8a epv;\x8a terrain_alt;\x86 lat_lon_reset_counter;\x86 alt_reset_counter;\x8c terrain_alt_valid;\x8c dead_reckoning;\x86[4] _padding0;";

ORB_DEFINE(vehicle_global_position, struct vehicle_global_position_s, 60, __orb_vehicle_global_position_fields, static_cast<uint8_t>(ORB_ID::vehicle_global_position));
ORB_DEFINE(vehicle_global_position_groundtruth, struct vehicle_global_position_s, 60, __orb_vehicle_global_position_fields, static_cast<uint8_t>(ORB_ID::vehicle_global_position_groundtruth));
ORB_DEFINE(external_ins_global_position, struct vehicle_global_position_s, 60, __orb_vehicle_global_position_fields, static_cast<uint8_t>(ORB_ID::external_ins_global_position));
ORB_DEFINE(estimator_global_position, struct vehicle_global_position_s, 60, __orb_vehicle_global_position_fields, static_cast<uint8_t>(ORB_ID::estimator_global_position));


void print_message(const orb_metadata *meta, const vehicle_global_position_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
