
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file D:\nextpilot\nextpilot-flight-control-public\msgs\uorb_msgs\VehicleOpticalFlowVel.msg */


#include <rtdbg.h>
#include <inttypes.h>
//#include <px4_platform_common/log.h>
//#include <px4_platform_common/defines.h>
#include <topics/vehicle_optical_flow_vel.h>
#include <topics/uORBTopics.hpp>
#include <hrtimer.h>
//#include <lib/drivers/device/Device.hpp>
//#include <lib/matrix/matrix/math.hpp>
//#include <lib/mathlib/mathlib.h>

constexpr char __orb_vehicle_optical_flow_vel_fields[] = "\x89 timestamp;\x89 timestamp_sample;\x8a[2] vel_body;\x8a[2] vel_ne;\x8a[2] flow_uncompensated_integral;\x8a[2] flow_compensated_integral;\x8a[3] gyro_rate;\x8a[3] gyro_rate_integral;";

ORB_DEFINE(estimator_optical_flow_vel, struct vehicle_optical_flow_vel_s, 72, __orb_vehicle_optical_flow_vel_fields, static_cast<uint8_t>(ORB_ID::estimator_optical_flow_vel));
ORB_DEFINE(vehicle_optical_flow_vel, struct vehicle_optical_flow_vel_s, 72, __orb_vehicle_optical_flow_vel_fields, static_cast<uint8_t>(ORB_ID::vehicle_optical_flow_vel));


void print_message(const orb_metadata *meta, const vehicle_optical_flow_vel_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
