
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file D:\nextpilot\nextpilot-flight-control-public\msgs\uorb_msgs\VehicleImuStatus.msg */


#include <rtdbg.h>
#include <inttypes.h>
//#include <px4_platform_common/log.h>
//#include <px4_platform_common/defines.h>
#include <topics/vehicle_imu_status.h>
#include <topics/uORBTopics.hpp>
#include <hrtimer.h>
//#include <lib/drivers/device/Device.hpp>
//#include <lib/matrix/matrix/math.hpp>
//#include <lib/mathlib/mathlib.h>

constexpr char __orb_vehicle_imu_status_fields[] = "\x89 timestamp;\x88 accel_device_id;\x88 gyro_device_id;\x88[3] accel_clipping;\x88[3] gyro_clipping;\x88 accel_error_count;\x88 gyro_error_count;\x8a accel_rate_hz;\x8a gyro_rate_hz;\x8a accel_raw_rate_hz;\x8a gyro_raw_rate_hz;\x8a accel_vibration_metric;\x8a gyro_vibration_metric;\x8a delta_angle_coning_metric;\x8a[3] mean_accel;\x8a[3] mean_gyro;\x8a[3] var_accel;\x8a[3] var_gyro;\x8a temperature_accel;\x8a temperature_gyro;\x86[4] _padding0;";

ORB_DEFINE(vehicle_imu_status, struct vehicle_imu_status_s, 132, __orb_vehicle_imu_status_fields, static_cast<uint8_t>(ORB_ID::vehicle_imu_status));


void print_message(const orb_metadata *meta, const vehicle_imu_status_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
