
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file D:\nextpilot\nextpilot-flight-control-public\msgs\uorb_msgs\Wind.msg */


#pragma once


#include <uORB.h>


#ifndef __cplusplus

#endif


#ifdef __cplusplus
struct __EXPORT wind_s {
#else
struct wind_s {
#endif
	uint64_t timestamp;
	uint64_t timestamp_sample;
	float windspeed_north;
	float windspeed_east;
	float variance_north;
	float variance_east;
	float tas_innov;
	float tas_innov_var;
	float beta_innov;
	float beta_innov_var;


#ifdef __cplusplus

#endif
};

#ifdef __cplusplus
namespace nextpilot {
	namespace msg {
		using Wind = wind_s;
	} // namespace msg
} // namespace nextpilot
#endif

/* register this as object request broker structure */
ORB_DECLARE(wind);
ORB_DECLARE(estimator_wind);


#ifdef __cplusplus
void print_message(const orb_metadata *meta, const wind_s& message);
#endif
