
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file D:\nextpilot\nextpilot-flight-control-public\msgs\uorb_msgs\Wind.msg */


#include <rtdbg.h>
#include <inttypes.h>
//#include <px4_platform_common/log.h>
//#include <px4_platform_common/defines.h>
#include <topics/wind.h>
#include <topics/uORBTopics.hpp>
#include <hrtimer.h>
//#include <lib/drivers/device/Device.hpp>
//#include <lib/matrix/matrix/math.hpp>
//#include <lib/mathlib/mathlib.h>

constexpr char __orb_wind_fields[] = "\x89 timestamp;\x89 timestamp_sample;\x8a windspeed_north;\x8a windspeed_east;\x8a variance_north;\x8a variance_east;\x8a tas_innov;\x8a tas_innov_var;\x8a beta_innov;\x8a beta_innov_var;";

ORB_DEFINE(wind, struct wind_s, 48, __orb_wind_fields, static_cast<uint8_t>(ORB_ID::wind));
ORB_DEFINE(estimator_wind, struct wind_s, 48, __orb_wind_fields, static_cast<uint8_t>(ORB_ID::estimator_wind));


void print_message(const orb_metadata *meta, const wind_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
