import os
import sys
from building import *


cwd = GetCurrentDir()

inc = []
src = [
    "launchdetection/LaunchDetector.cpp",
    "runway_takeoff/RunwayTakeoff.cpp",
    "FixedwingPositionControl.cpp",
]

objs = DefineGroup("fcs/fw_pos_control", src, depend=["FCS_UISNG_FW_POS_CONTROL"])

Return("objs")
