import os
import rtconfig
from building import *


cwd = GetCurrentDir()

inc = [cwd]
src = ["pid.cpp"]


objs = DefineGroup("lib/control", src, depend=["PKG_USING_PID"], CPPPATH=inc)


Return("objs")
