import os
import sys
import rtconfig
import subprocess
from building import *


cwd = GetCurrentDir()

# 自动更新版本信息
cmd = [
    sys.executable,
    os.path.normpath(os.path.join(cwd, "update_version_header.py")),
    os.path.normpath(os.path.join(cwd, "board_fw_version_autogen.h")),
    "--verbose",
]
subprocess.call(cmd)

# 添加当前文件夹下的代码
inc = [cwd]
src = Glob("*.c")  # + Glob("*.cpp")


objs = DefineGroup("pkg/version", src, depend=["PKG_USING_BOARD_VERSION"], CPPPATH=inc)


Return("objs")
