import os
import sys
import rtconfig
from building import *


cwd = GetCurrentDir()

# 自动更新版本信息
pycmd = os.path.basename(sys.executable)
os.system("%s %s/update_version_header.py -v %s/board_fw_version_autogen.h" % (pycmd, cwd, cwd))

# 添加当前文件夹下的代码
inc = [cwd]
src = Glob("*.c")  # + Glob("*.cpp")


objs = DefineGroup("pkg/version", src, depend=["PKG_USING_BOARD_VERSION"], CPPPATH=inc)


Return("objs")
