import os
import sys
import subprocess
from building import *


cwd = GetCurrentDir()

# 生成romfs.c文件
cmd = [
    sys.executable,
    os.path.normpath(os.path.join(cwd, r"../../../rtos/rt-thread/tools/mkromfs.py")),  # mkromfs.py
    os.path.normpath(os.path.join(cwd, "root")),  # rootpath
    os.path.normpath(os.path.join(cwd, "romfs.c")),
]
subprocess.call(cmd)

inc = []
src = ["romfs.c", "romfs_mnt.c"]

objs = DefineGroup("rtt/Filesystem", src, depend=["SYS_USING_ROMFS"])


Return("objs")
