import os
import rtconfig
from building import *


cwd = GetCurrentDir()

inc = [cwd]
src = ["Ringbuffer.cpp"]

objs = DefineGroup("lib/ring_buffer", src, depend=["PKG_USING_RING_BUFFER"], CPPPATH=inc)

Return("objs")
