# RT-Thread building script for bridge

import os
from building import *

objs = []
if GetDepend(["BSP_USING_QEMU"]):
    cwd = GetCurrentDir()

    for d in os.listdir(cwd):
        path = os.path.join(cwd, d)
        if os.path.isfile(os.path.join(path, "SConscript")):
            objs += SConscript(os.path.join(d, "SConscript"), variant_dir="#/build/bsp/" + d, duplicate=0)
else:
    objs = []

Return("objs")
