import os
import sys
from building import *


cwd = GetCurrentDir()

inc = []
src = Glob("*.cpp", exclude="*_test.cpp")

objs = DefineGroup("fcs/mc_hover_thrust_estimator", src, depend=["FCS_USING_MC_HOVER_THRUST_ESTIMATOR"])

Return("objs")
