import os
import rtconfig
from building import *


cwd = GetCurrentDir()

inc = [cwd]
src = Glob("*.c") + Glob("*.cpp")

objs = DefineGroup("pkg/container", src, depend=["PKG_USING_CONTAINER"], CPPPATH=inc)


Return("objs")
