import os
import rtconfig
from building import *

objs = []
cwd = GetCurrentDir()

inc = [cwd]
src = []

if GetDepend(["PARAM_USING_STORAGE_FILE"]):
    src += ["param_storage_file.c"]

if GetDepend(["PARAM_USING_STORAGE_FM25V02"]):
    src += ["param_storage_fm25v02.c"]

objs += DefineGroup("pkg/param", src, depend=[""], CPPPATH=inc)

Return("objs")
