import os
import sys
from building import *

objs = []

if GetDepend(["FCS_USING_MC_POS_CONTROL"]):
    cwd = GetCurrentDir()
    inc = []
    src = [
        "MulticopterPositionControl.cpp",
        "Takeoff/Takeoff.cpp",
        "PositionControl/ControlMath.cpp",
        "PositionControl/PositionControl.cpp",
    ]

    objs = DefineGroup("fcs/mc_att_control", src, depend=[""])
else:
    pass

Return("objs")
