import os
import rtconfig
from building import *

cwd = GetCurrentDir()

src = Glob("*.c")
inc = [cwd]

objs = DefineGroup("lib/libcrc", src, depend=["LIB_USING_LIBCRC"], CPPPATH=inc)

Return("objs")
