import os
import rtconfig
from building import *

cwd = GetCurrentDir()

inc = [cwd]
src = Glob("*.cpp") + Glob("1102_sih_standard_vtol/1102_sih_standard_vtol.cpp")

objs = DefineGroup("air", src, depend=["SYS_USING_AIRFRAME"], CPPPATH=inc)

for d in os.listdir(cwd):
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, "SConscript")):
        objs += SConscript(os.path.join(d, "SConscript"))

Return("objs")
