import os
import rtconfig
from building import *

cwd = GetCurrentDir()
objs = []

if not GetDepend(["SYS_USING_AIRFRAME"]):
    Return("objs")


src = Glob("*.cpp")
objs += DefineGroup("air", src, depend=["SYS_USING_AIRFRAME"])

for d in os.listdir(cwd):
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, "SConscript")):
        objs += SConscript(os.path.join(d, "SConscript"))

Return("objs")
