import os
import rtconfig
from building import *


cwd = GetCurrentDir()

inc = [cwd]
src = Glob("*.c")

objs = DefineGroup("lib/common", src, depend=["PKG_USING_HRTIMER_V1"], CPPPATH=inc)


Return("objs")
