import os
import rtconfig
from building import *


cwd = GetCurrentDir()

inc = [cwd]
src = ["hrtimer.c"]

if GetDepend(["HRT_USING_SYSTICK"]):
    src += ["hrt_using_systick.c"]

if GetDepend(["HRT_USING_HWTIMER"]):
    src += ["hrt_using_hwtimer.c"]


objs = DefineGroup("lib/common", src, depend=["PKG_USING_HRTIMER_V2"], CPPPATH=inc)


Return("objs")
