#ifndef _PARAMETERS_AUTOGEN_HPP_
#define _PARAMETERS_AUTOGEN_HPP_

#include <math.h>
#include <stdint.h>
#include <param.h>

// DO NOT EDIT
// This file is autogenerated from *_params.toml

namespace nextpilot { 

/// Enum with all parameters
enum class params : uint16_t {
	AA = 0,
	BB = 1,
	MAV_0_MODE = 2,
	MAV_0_RATE = 3,
	MAV_1_MODE = 4,
	MAV_1_RATE = 5,
	MAV_2_MODE = 6,
	MAV_2_RATE = 7,
	MAV_3_MODE = 8,
	MAV_4_MODE = 9,
	ZZ = 10,
	MAX_COUNT
};

static constexpr param_info_s parameters[] = {
	{.name = "AA",.type = 4,.value = {.f32 = 0},.flag = {.value = 0}},
	{.name = "BB",.type = 4,.value = {.f32 = 0},.flag = {.value = 0}},
	{.name = "MAV_0_MODE",.type = 3,.value = {.i32 = 0},.flag = {.value = 0}},
	{.name = "MAV_0_RATE",.type = 3,.value = {.i32 = 0},.flag = {.value = 0}},
	{.name = "MAV_1_MODE",.type = 3,.value = {.i32 = 2},.flag = {.value = 0}},
	{.name = "MAV_1_RATE",.type = 3,.value = {.i32 = 2},.flag = {.value = 0}},
	{.name = "MAV_2_MODE",.type = 3,.value = {.i32 = 0},.flag = {.value = 0}},
	{.name = "MAV_2_RATE",.type = 3,.value = {.i32 = 0},.flag = {.value = 0}},
	{.name = "MAV_3_MODE",.type = 3,.value = {.i32 = 0},.flag = {.value = 0}},
	{.name = "MAV_4_MODE",.type = 3,.value = {.i32 = 0},.flag = {.value = 0}},
	{.name = "ZZ",.type = 4,.value = {.f32 = 0},.flag = {.value = 0}},
};

} // namespace nextpilot

#endif // _PARAMETERS_AUTOGEN_HPP_