import os
import rtconfig
from building import *


cwd = GetCurrentDir()

inc = [cwd]
src = ["hysteresis.cpp"]

objs = DefineGroup("lib/control", src, depend=["PKG_USING_HYSTERESIS"], CPPPATH=inc)


Return("objs")
