import os
import rtconfig
from building import *

cwd = GetCurrentDir()

# 添加当前文件夹下的代码
src = Glob("*.c") + Glob("*.cpp")
inc = []

objs = DefineGroup("utest", src, depend=["TEST_MC_CTRL"], CPPPATH=inc)


Return("objs")
