import os
import rtconfig
from building import *


cwd = GetCurrentDir()

inc = [cwd]
src = ["terrain_estimator.cpp"]

objs = DefineGroup("pkg/terrain_estimation", src, depend=["PKG_USING_TERRAIN_ESTIMATOR"], CPPPATH=inc)


Return("objs")
