import os
import rtconfig
from building import *


cwd = GetCurrentDir()

inc = [cwd]
src = Glob("*.c") + Glob("*.cpp")


objs = DefineGroup("pkg/perf", src, depend=["PKG_USING_PERF"], CPPPATH=inc)


Return("objs")
