import os
import sys
from building import *


cwd = GetCurrentDir()

inc = []
src = Glob("*.cpp", exclude="*_test.cpp")

objs = DefineGroup("fcs/land_detector", src, depend=["FCS_USING_LAND_DETECTOR"])


Return("objs")
