import os
import sys
from building import *

objs = []

if GetDepend(["FCS_USING_LAND_DETECTOR"]):
    cwd = GetCurrentDir()
    inc = []
    src = Glob("*.cpp", exclude="*_test.cpp")

    objs = DefineGroup("fcs/land_detector", src, depend=[""])
else:
    pass

Return("objs")
