import os
import rtconfig
from building import *

objs = []

cwd = GetCurrentDir()

objs += DefineGroup(name="app", src=[], depend=[], CPPPATH=[cwd])

for d in os.listdir(cwd):
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, "SConscript")):
        # print(os.path.join(d, 'SConscript'))
        objs += SConscript(os.path.join(d, "SConscript"))

Return("objs")
