import os
import rtconfig
from building import *

cwd = GetCurrentDir()
inc = [cwd]
src = []

if GetDepend(["ULOG_BACKEND_USING_FILES"]):
    src += ["ulog_files_backend.c"]

if GetDepend(["ULOG_BACKEND_USING_UORB"]):
    src += ["ulog_uorb_backend.c"]

objs = DefineGroup("pkg/ulog_be", src, depend=[""], CPPPATH=inc)

Return("objs")
