import os
import sys
import rtconfig
from building import *


cwd = GetCurrentDir()

inc = []
src = Glob("VariableLengthRingbuffer.cpp")


objs = DefineGroup("pkg/version", src, depend=["PKG_USING_VAR_LEN_RINGBUFFER"], CPPPATH=inc)


Return("objs")
