import os
import rtconfig
from building import *

objs = []

if not GetDepend(["SOC_FAMILY_STM32"]):
    Return("objs")

cwd = GetCurrentDir()

for d in os.listdir(cwd):
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, "SConscript")):
        # print(os.path.join(d, 'SConscript'))
        objs += SConscript(os.path.join(d, "SConscript"), variant_dir="#/build/bsps/libraries/" + d, duplicate=0)
        # objs += SConscript(os.path.join(d, "SConscript"))

Return("objs")
