import os
import rtconfig
from building import *


cwd = GetCurrentDir()

inc = [cwd]
src = ["rotation.cpp"]

objs = DefineGroup("lib/rotation", src, depend=["PKG_USING_ROTATION"], CPPPATH=inc)


Return("objs")
