import os
import sys
import rtconfig

if os.getenv("RTT_ROOT"):
    RTT_ROOT = os.getenv("RTT_ROOT")
else:
    RTT_ROOT = os.path.normpath(os.getcwd() + "/../../../rtos/rt-thread")

sys.path = sys.path + [os.path.join(RTT_ROOT, "tools")]
try:
    from building import *
except:
    print("Cannot found RT-Thread root directory, please check RTT_ROOT")
    print(RTT_ROOT)
    exit(-1)

TARGET = "rtthread." + rtconfig.TARGET_EXT
DefaultEnvironment(tools=[])
if rtconfig.PLATFORM == "armcc":
    env = Environment(
        tools=["mingw"],
        AS=rtconfig.AS,
        ASFLAGS=rtconfig.AFLAGS,
        CC=rtconfig.CC,
        CCFLAGS=rtconfig.CFLAGS,
        CXX=rtconfig.CXX,
        CXXFLAGS=rtconfig.CXXFLAGS,
        AR=rtconfig.AR,
        ARFLAGS="-rc",
        LINK=rtconfig.LINK,
        LINKFLAGS=rtconfig.LFLAGS,
        # overwrite cflags, because cflags has '--C99'
        CXXCOM="$CXX -o $TARGET --cpp -c $CXXFLAGS $_CCCOMCOM $SOURCES",
    )
else:
    env = Environment(
        tools=["mingw"],
        AS=rtconfig.AS,
        ASFLAGS=rtconfig.AFLAGS,
        CC=rtconfig.CC,
        CCFLAGS=rtconfig.CFLAGS,
        CXX=rtconfig.CXX,
        CXXFLAGS=rtconfig.CXXFLAGS,
        AR=rtconfig.AR,
        ARFLAGS="-rc",
        LINK=rtconfig.LINK,
        LINKFLAGS=rtconfig.LFLAGS,
        CXXCOM="$CXX -o $TARGET -c $CXXFLAGS $_CCCOMCOM $SOURCES",
    )

env.PrependENVPath("PATH", rtconfig.EXEC_PATH)

if rtconfig.PLATFORM in ["iccarm"]:
    env.Replace(CCCOM=["$CC $CCFLAGS $CPPFLAGS $_CPPDEFFLAGS $_CPPINCFLAGS -o $TARGET $SOURCES"])
    env.Replace(ARFLAGS=[""])
    env.Replace(LINKCOM=env["LINKCOM"] + " --map rtthread.map")

Export("RTT_ROOT")
Export("rtconfig")


SDK_LIB = os.path.normpath(os.path.join(os.getcwd(), "../../../rtos/platform/nxp"))
print(SDK_LIB)
Export("SDK_LIB")

# prepare building environment
objs = PrepareBuilding(env, RTT_ROOT, has_libcpu=False)

rtconfig.BSP_LIBRARY_TYPE = "MIMXRT1170"

# include libraries
objs.extend(SConscript(os.path.join(SDK_LIB, "MIMXRT1170", "SConscript")))

# include drivers
objs.extend(SConscript(os.path.join(SDK_LIB, "drivers", "SConscript")))

# make a building
DoBuilding(TARGET, objs)
