import os
import sys
from building import *

cwd = GetCurrentDir()

inc = []
src = Glob("*.cpp", exclude="*_test.cpp")

objs = DefineGroup("fcs/fw_att_control", src, depend=["FCS_USING_FW_ATT_CONTROL"])

Return("objs")
