import os
import sys
from building import *

cwd = GetCurrentDir()

inc = []
src = Glob("*.cpp", exclude="*_test.cpp")

objs = DefineGroup("ins/attitude_estimator_q", src, depend=["INS_USING_ATTITUDE_ESTIMATOR_Q"])

Return("objs")
