import os
import rtconfig
from building import *


cwd = GetCurrentDir()

inc = [cwd]
src = ["BezierN.cpp", "BezierQuad.cpp"]

objs = DefineGroup("lib/control", src, depend=["PKG_USING_BEZIER"], CPPPATH=inc)


Return("objs")
