import os
import rtconfig
from building import *

cwd = GetCurrentDir()

src = Glob("*.c") + Glob("*.cpp")
inc = []

objs = DefineGroup("utest", src, depend=["TEST_PKG_UORB"], CPPPATH=inc)


Return("objs")
