import os
import rtconfig
from building import *


cwd = GetCurrentDir()

inc = [cwd]
src = ["terrain_estimatorcpp"]

objs = DefineGroup("lib/control", src, depend=["PKG_USING_TERRAIN_ESTIMATION"], CPPPATH=inc)

Return("objs")
