import os
import rtconfig
from building import *


cwd = GetCurrentDir()

inc = []
src = Glob("*.cpp")

objs = DefineGroup("lib/drivers", src, depend=["PKG_USING_BATTERY"], CPPPATH=inc)


Return("objs")
