import os
import sys
from building import *

objs = []

if GetDepend(["PKG_MC_AUTOTUNE_ATTITUDE_CONTROL"]):
    cwd = GetCurrentDir()
    inc = []
    src = Glob("*.cpp")

    objs = DefineGroup("fcs/mc_autotune_attitude_control", src, depend=[""])
else:
    pass

Return("objs")
