import os
import sys
from building import *


cwd = GetCurrentDir()

inc = []
src = Glob("*.cpp")

objs = DefineGroup("fcs/mc_autotune_attitude_control", src, depend=["FCS_MC_AUTOTUNE_ATTITUDE_CONTROL"])

Return("objs")
