import os
import sys
from building import *


cwd = GetCurrentDir()

inc = []
src = Glob("*.cpp")

objs = DefineGroup("fcs/mc_rate_control", src, depend=["FCS_USING_MC_RATE_CONTROL"])

Return("objs")
