import os
import sys
from building import *


objs = []

if GetDepend(["FCS_MC_RATE_CONTROL__"]):
    cwd = GetCurrentDir()
    inc = []
    src = Glob("*.cpp") + Glob("rate_control/rate_control.cpp")

    objs = DefineGroup("fcs/mc_rate_control", src, depend=[""])
else:
    pass

Return("objs")
