import os
import rtconfig
from building import *

objs = []

if GetDepend(["PKG_USING_GEO"]):
    cwd = GetCurrentDir()
    src = ["geo.cpp"]
    inc = [cwd]

    objs += DefineGroup("lib/geo", src, depend=[""], CPPPATH=inc)

    for d in os.listdir(cwd):
        path = os.path.join(cwd, d)
        if os.path.isfile(os.path.join(path, "SConscript")):
            objs += SConscript(os.path.join(d, "SConscript"))
else:
    objs = []

Return("objs")
