import os
import rtconfig
from building import *


cwd = GetCurrentDir()

inc = [cwd]
src = ["ECL_L1_Pos_Controller.cpp"]

objs = DefineGroup("lib/control", src, depend=["PKG_USING_ECL"], CPPPATH=inc)


Return("objs")
