import os
import sys
from building import *

cwd = GetCurrentDir()

inc = []
src = Glob("*.cpp", exclude="*_test.cpp")

objs = DefineGroup("ins/airspeed_selector", src, depend=["INS_USING_AIRSPEED_SELECTOR"])

Return("objs")
