import os
import rtconfig
from building import *


cwd = GetCurrentDir()

inc = [cwd]
src = []

objs = DefineGroup("pkg/field_sensor_bias_estimator", src, depend=["PKG_USING_FIELD_SENSOR_BIAS_ESTIMATOR"], CPPPATH=inc)

Return("objs")
