import os
import rtconfig
from building import *


cwd = GetCurrentDir()


inc = [cwd]
src = Glob("*.cpp") + Glob("block/*.cpp")

objs = DefineGroup("pkg/controllib", src, depend=["PKG_USING_CONTROLLIB"], CPPPATH=inc)


Return("objs")
