import os
import sys
from building import *


cwd = GetCurrentDir()

inc = []
src = ["ManualControl.cpp", "ManualControlSelector.cpp"]

objs = DefineGroup("fcs/manual_control", src, depend=["FCS_USING_MANUAL_CONTROL"])

Return("objs")
