import os
import rtconfig
from building import *


cwd = GetCurrentDir()

inc = [cwd]
src = Glob("*.cpp")

objs = DefineGroup("lib/estimator", src, depend=["PKG_USING_SENSOR_CALIBRATION"], CPPPATH=inc)


Return("objs")
