import os
import sys
from building import *

objs = []

if GetDepend(["FCS_USING_MC_ATT_CONTROL"]):
    cwd = GetCurrentDir()
    inc = []
    src = Glob("*.cpp") + Glob("AttitudeControl/AttitudeControl.cpp")

    objs = DefineGroup("fcs/mc_att_control", src, depend=[""])
else:
    pass

Return("objs")
