import os
import sys
from building import *

cwd = GetCurrentDir()

inc = []
src = Glob("*.cpp") + Glob("AttitudeControl/AttitudeControl.cpp")

objs = DefineGroup("fcs/mc_att_control", src, depend=["FCS_USING_MC_ATT_CONTROL"])

Return("objs")
