import os
import rtconfig
from building import *

cwd = GetCurrentDir()

inc = [cwd]
src = []

objs = DefineGroup("pkg/pid_design", src, depend=["PKG_USING_PID_DESIGN"], CPPPATH=inc)


Return("objs")
