import os
import sys
import subprocess
from building import *

cwd = GetCurrentDir()

inc = []
src = Glob("*.cpp")

objs = DefineGroup("drv/safty_button", src, depend=["DRV_USING_SAFETY_BUTTON"])

Return("objs")
