import os
import sys
from building import *

cwd = GetCurrentDir()

inc = []
src = Glob("*.cpp", exclude="*_test.cpp")

objs = DefineGroup("ins/sensors", src, depend=["SENSORS_VEHICLE_MAGNETOMETER"])

Return("objs")
