import os
import rtconfig
from building import *


cwd = GetCurrentDir()

inc = [cwd]
src = [
    "ManualVelocitySmoothingXY.cpp",
    "ManualVelocitySmoothingZ.cpp",
    "PositionSmoothing.cpp",
    "VelocitySmoothing.cpp",
]

objs = DefineGroup("lib/control", src, depend=["PKG_USING_MOTION_PLANNING"], CPPPATH=inc)


Return("objs")
