
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file DifferentialPressure.msg */


#include <rtdbg.h>
#include <inttypes.h>
#include <hrtimer.h>
#include <topics/uORBTopics.hpp>
#include <topics/differential_pressure.h>

constexpr char __orb_differential_pressure_fields[] = "\x89 timestamp;\x89 timestamp_sample;\x88 device_id;\x8a differential_pressure_pa;\x8a temperature;\x88 error_count;";

ORB_DEFINE(differential_pressure, struct differential_pressure_s, 32, __orb_differential_pressure_fields, static_cast<uint8_t>(ORB_ID::differential_pressure));


void print_message(const orb_metadata *meta, const differential_pressure_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
