
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file EstimatorSelectorStatus.msg */


#include <rtdbg.h>
#include <inttypes.h>
#include <hrtimer.h>
#include <topics/uORBTopics.hpp>
#include <topics/estimator_selector_status.h>

constexpr char __orb_estimator_selector_status_fields[] = "\x89 timestamp;\x89 last_instance_change;\x88 instance_changed_count;\x88 accel_device_id;\x88 baro_device_id;\x88 gyro_device_id;\x88 mag_device_id;\x8a[9] combined_test_ratio;\x8a[9] relative_test_ratio;\x8a[4] accumulated_gyro_error;\x8a[4] accumulated_accel_error;\x86 primary_instance;\x86 instances_available;\x8c[9] healthy;\x8c gyro_fault_detected;\x8c accel_fault_detected;\x86[7] _padding0;";

ORB_DEFINE(estimator_selector_status, struct estimator_selector_status_s, 153, __orb_estimator_selector_status_fields, static_cast<uint8_t>(ORB_ID::estimator_selector_status));


void print_message(const orb_metadata *meta, const estimator_selector_status_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
