
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file EstimatorStates.msg */


#include <rtdbg.h>
#include <inttypes.h>
#include <hrtimer.h>
#include <topics/uORBTopics.hpp>
#include <topics/estimator_states.h>

constexpr char __orb_estimator_states_fields[] = "\x89 timestamp;\x89 timestamp_sample;\x8a[24] states;\x8a[24] covariances;\x86 n_states;\x86[7] _padding0;";

ORB_DEFINE(estimator_states, struct estimator_states_s, 209, __orb_estimator_states_fields, static_cast<uint8_t>(ORB_ID::estimator_states));


void print_message(const orb_metadata *meta, const estimator_states_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
