
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file EstimatorSensorBias.msg */

#pragma once

#include <uORB.h>

#ifndef __cplusplus
#endif // __cplusplus


#ifdef __cplusplus
struct __EXPORT estimator_sensor_bias_s {
#else
struct estimator_sensor_bias_s {
#endif // __cplusplus
	uint64_t timestamp;
	uint64_t timestamp_sample;
	uint32_t gyro_device_id;
	float gyro_bias[3];
	float gyro_bias_limit;
	float gyro_bias_variance[3];
	uint32_t accel_device_id;
	float accel_bias[3];
	float accel_bias_limit;
	float accel_bias_variance[3];
	uint32_t mag_device_id;
	float mag_bias[3];
	float mag_bias_limit;
	float mag_bias_variance[3];
	bool gyro_bias_valid;
	bool gyro_bias_stable;
	bool accel_bias_valid;
	bool accel_bias_stable;
	bool mag_bias_valid;
	bool mag_bias_stable;
	uint8_t _padding0[2]; // required for logger

#ifdef __cplusplus
#endif // __cplusplus
};

#ifdef __cplusplus
namespace nextpilot {
	namespace msg {
		using EstimatorSensorBias = estimator_sensor_bias_s;
	} // namespace msg
} // namespace nextpilot
#endif // __cplusplus

/* register this as object request broker structure */
ORB_DECLARE(estimator_sensor_bias);

#ifdef __cplusplus
void print_message(const orb_metadata *meta, const estimator_sensor_bias_s& message);
#endif // __cplusplus
