
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file GpsInjectData.msg */

#pragma once

#include <uORB.h>

#ifndef __cplusplus
#define GPS_INJECT_DATA_ORB_QUEUE_LENGTH 8
#define GPS_INJECT_DATA_MAX_INSTANCES 2
#endif // __cplusplus


#ifdef __cplusplus
struct __EXPORT gps_inject_data_s {
#else
struct gps_inject_data_s {
#endif // __cplusplus
	uint64_t timestamp;
	uint32_t device_id;
	uint16_t len;
	uint8_t flags;
	uint8_t data[300];
	uint8_t _padding0[5]; // required for logger

#ifdef __cplusplus
	static constexpr uint8_t ORB_QUEUE_LENGTH = 8;
	static constexpr uint8_t MAX_INSTANCES = 2;
#endif // __cplusplus
};

#ifdef __cplusplus
namespace nextpilot {
	namespace msg {
		using GpsInjectData = gps_inject_data_s;
	} // namespace msg
} // namespace nextpilot
#endif // __cplusplus

/* register this as object request broker structure */
ORB_DECLARE(gps_inject_data);

#ifdef __cplusplus
void print_message(const orb_metadata *meta, const gps_inject_data_s& message);
#endif // __cplusplus
