
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file HomePosition.msg */

#pragma once

#include <uORB.h>

#ifndef __cplusplus
#endif // __cplusplus


#ifdef __cplusplus
struct __EXPORT home_position_s {
#else
struct home_position_s {
#endif // __cplusplus
	uint64_t timestamp;
	double lat;
	double lon;
	float alt;
	float x;
	float y;
	float z;
	float yaw;
	bool valid_alt;
	bool valid_hpos;
	bool valid_lpos;
	bool manual_home;

#ifdef __cplusplus
#endif // __cplusplus
};

#ifdef __cplusplus
namespace nextpilot {
	namespace msg {
		using HomePosition = home_position_s;
	} // namespace msg
} // namespace nextpilot
#endif // __cplusplus

/* register this as object request broker structure */
ORB_DECLARE(home_position);

#ifdef __cplusplus
void print_message(const orb_metadata *meta, const home_position_s& message);
#endif // __cplusplus
