
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file LandingTargetInnovations.msg */

#pragma once

#include <uORB.h>

#ifndef __cplusplus
#endif // __cplusplus


#ifdef __cplusplus
struct __EXPORT landing_target_innovations_s {
#else
struct landing_target_innovations_s {
#endif // __cplusplus
	uint64_t timestamp;
	float innov_x;
	float innov_y;
	float innov_cov_x;
	float innov_cov_y;

#ifdef __cplusplus
#endif // __cplusplus
};

#ifdef __cplusplus
namespace nextpilot {
	namespace msg {
		using LandingTargetInnovations = landing_target_innovations_s;
	} // namespace msg
} // namespace nextpilot
#endif // __cplusplus

/* register this as object request broker structure */
ORB_DECLARE(landing_target_innovations);

#ifdef __cplusplus
void print_message(const orb_metadata *meta, const landing_target_innovations_s& message);
#endif // __cplusplus
