
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file LandingTargetPose.msg */


#include <rtdbg.h>
#include <inttypes.h>
#include <hrtimer.h>
#include <topics/uORBTopics.hpp>
#include <topics/landing_target_pose.h>

constexpr char __orb_landing_target_pose_fields[] = "\x89 timestamp;\x8a x_rel;\x8a y_rel;\x8a z_rel;\x8a vx_rel;\x8a vy_rel;\x8a cov_x_rel;\x8a cov_y_rel;\x8a cov_vx_rel;\x8a cov_vy_rel;\x8a x_abs;\x8a y_abs;\x8a z_abs;\x8c is_static;\x8c rel_pos_valid;\x8c rel_vel_valid;\x8c abs_pos_valid;\x86[4] _padding0;";

ORB_DEFINE(landing_target_pose, struct landing_target_pose_s, 60, __orb_landing_target_pose_fields, static_cast<uint8_t>(ORB_ID::landing_target_pose));


void print_message(const orb_metadata *meta, const landing_target_pose_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
