
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file NpfgStatus.msg */

#pragma once

#include <uORB.h>

#ifndef __cplusplus
#endif // __cplusplus


#ifdef __cplusplus
struct __EXPORT npfg_status_s {
#else
struct npfg_status_s {
#endif // __cplusplus
	uint64_t timestamp;
	float lat_accel;
	float lat_accel_ff;
	float bearing_feas;
	float bearing_feas_on_track;
	float signed_track_error;
	float track_error_bound;
	float airspeed_ref;
	float bearing;
	float heading_ref;
	float min_ground_speed_ref;
	float adapted_period;
	float p_gain;
	float time_const;
	uint8_t wind_est_valid;
	uint8_t _padding0[3]; // required for logger

#ifdef __cplusplus
#endif // __cplusplus
};

#ifdef __cplusplus
namespace nextpilot {
	namespace msg {
		using NpfgStatus = npfg_status_s;
	} // namespace msg
} // namespace nextpilot
#endif // __cplusplus

/* register this as object request broker structure */
ORB_DECLARE(npfg_status);

#ifdef __cplusplus
void print_message(const orb_metadata *meta, const npfg_status_s& message);
#endif // __cplusplus
