
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file OrbTestMedium.msg */


#include <rtdbg.h>
#include <inttypes.h>
#include <hrtimer.h>
#include <topics/uORBTopics.hpp>
#include <topics/orb_test_medium.h>

constexpr char __orb_orb_test_medium_fields[] = "\x89 timestamp;\x84 val;\x86[64] junk;\x86[4] _padding0;";

ORB_DEFINE(orb_test_medium, struct orb_test_medium_s, 76, __orb_orb_test_medium_fields, static_cast<uint8_t>(ORB_ID::orb_test_medium));
ORB_DEFINE(orb_test_medium_multi, struct orb_test_medium_s, 76, __orb_orb_test_medium_fields, static_cast<uint8_t>(ORB_ID::orb_test_medium_multi));
ORB_DEFINE(orb_test_medium_wrap_around, struct orb_test_medium_s, 76, __orb_orb_test_medium_fields, static_cast<uint8_t>(ORB_ID::orb_test_medium_wrap_around));
ORB_DEFINE(orb_test_medium_queue, struct orb_test_medium_s, 76, __orb_orb_test_medium_fields, static_cast<uint8_t>(ORB_ID::orb_test_medium_queue));
ORB_DEFINE(orb_test_medium_queue_poll, struct orb_test_medium_s, 76, __orb_orb_test_medium_fields, static_cast<uint8_t>(ORB_ID::orb_test_medium_queue_poll));


void print_message(const orb_metadata *meta, const orb_test_medium_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
