
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file PositionControllerLandingStatus.msg */


#include <rtdbg.h>
#include <inttypes.h>
#include <hrtimer.h>
#include <topics/uORBTopics.hpp>
#include <topics/position_controller_landing_status.h>

constexpr char __orb_position_controller_landing_status_fields[] = "\x89 timestamp;\x8a lateral_touchdown_offset;\x8c flaring;\x86 abort_status;\x86[2] _padding0;";

ORB_DEFINE(position_controller_landing_status, struct position_controller_landing_status_s, 14, __orb_position_controller_landing_status_fields, static_cast<uint8_t>(ORB_ID::position_controller_landing_status));


void print_message(const orb_metadata *meta, const position_controller_landing_status_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
