
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file PowerMonitor.msg */


#include <rtdbg.h>
#include <inttypes.h>
#include <hrtimer.h>
#include <topics/uORBTopics.hpp>
#include <topics/power_monitor.h>

constexpr char __orb_power_monitor_fields[] = "\x89 timestamp;\x8a voltage_v;\x8a current_a;\x8a power_w;\x83 rconf;\x83 rsv;\x83 rbv;\x83 rp;\x83 rc;\x83 rcal;\x83 me;\x83 al;\x86[4] _padding0;";

ORB_DEFINE(power_monitor, struct power_monitor_s, 36, __orb_power_monitor_fields, static_cast<uint8_t>(ORB_ID::power_monitor));


void print_message(const orb_metadata *meta, const power_monitor_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
