
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file RcChannels.msg */


#include <rtdbg.h>
#include <inttypes.h>
#include <hrtimer.h>
#include <topics/uORBTopics.hpp>
#include <topics/rc_channels.h>

constexpr char __orb_rc_channels_fields[] = "\x89 timestamp;\x89 timestamp_last_valid;\x8a[18] channels;\x88 frame_drop_count;\x86 channel_count;\x82[28] function;\x86 rssi;\x8c signal_lost;\x86[5] _padding0;";

ORB_DEFINE(rc_channels, struct rc_channels_s, 123, __orb_rc_channels_fields, static_cast<uint8_t>(ORB_ID::rc_channels));


void print_message(const orb_metadata *meta, const rc_channels_s& message)
{
	if (sizeof(message) != meta->o_size) {
		LOG_RAW("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	// orb_print_message_internal(meta, &message, true);
}
