
/*****************************************************************
 *     _   __             __   ____   _  __        __
 *    / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
 *   /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
 *  / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
 * /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
 *
 * Copyright All Reserved © 2015-2024 NextPilot Development Team
 ******************************************************************/

/* Auto-generated by genmsg_cpp from file UlogStreamAck.msg */

#pragma once

#include <uORB.h>

#ifndef __cplusplus
#define ULOG_STREAM_ACK_ACK_TIMEOUT 50
#define ULOG_STREAM_ACK_ACK_MAX_TRIES 50
#endif // __cplusplus


#ifdef __cplusplus
struct __EXPORT ulog_stream_ack_s {
#else
struct ulog_stream_ack_s {
#endif // __cplusplus
	uint64_t timestamp;
	uint16_t msg_sequence;
	uint8_t _padding0[6]; // required for logger

#ifdef __cplusplus
	static constexpr int32_t ACK_TIMEOUT = 50;
	static constexpr int32_t ACK_MAX_TRIES = 50;
#endif // __cplusplus
};

#ifdef __cplusplus
namespace nextpilot {
	namespace msg {
		using UlogStreamAck = ulog_stream_ack_s;
	} // namespace msg
} // namespace nextpilot
#endif // __cplusplus

/* register this as object request broker structure */
ORB_DECLARE(ulog_stream_ack);

#ifdef __cplusplus
void print_message(const orb_metadata *meta, const ulog_stream_ack_s& message);
#endif // __cplusplus
