import os
import rtconfig
from building import *

cwd = GetCurrentDir()

# 添加当前文件夹下的代码
src = Glob("*.c") + Glob("*.cpp")
inc = [cwd]

objs = DefineGroup("pkg/common", src, depend=["PKG_USING_QUEUE"], CPPPATH=inc)

Return("objs")
