import os
import rtconfig
from building import *


cwd = GetCurrentDir()

inc = [cwd]
src = ["TECS.cpp"]

objs = DefineGroup("lib/control", src, depend=["PKG_USING_TECS"], CPPPATH=inc)


Return("objs")
