import os
import sys
from building import *

cwd = GetCurrentDir()

inc = []
src = Glob("*.cpp", exclude="*_test.cpp") + Glob("sensors/*.cpp")

objs = DefineGroup("ins/local_position_estimator", src, depend=["INS_USING_LOCAL_POSITION_ESTIMATOR"])

Return("objs")
