import os
import sys
import subprocess
from building import *

cwd = GetCurrentDir()

generated_events_from_source_file = File("#/build/events_from_source.json").abspath
generated_events_common_enums_file = File("#build/events_common_with_enums.json").abspath
generated_events_combined_all_file = File("#/build/events_combined_all.json").abspath

all_src_files = {
    os.path.join(cwd, "../../apps"),
}


# Generating event json file from source
cmd = [
    sys.executable,
    os.path.join(cwd, "tools/process_events.py"),
    "--json",
    generated_events_from_source_file,
    "--src-path",
] + list(all_src_files)
if sys.version_info > (3, 0):
    subprocess.call(cmd)

# combine common.json with our enums for the code generation
cmd = [
    sys.executable,
    os.path.join(cwd, "libevents/scripts/combine.py"),
    os.path.join(cwd, "enums.json"),
    os.path.join(cwd, "libevents/events/common.json"),
    "--output",
    generated_events_common_enums_file,
]
if sys.version_info > (3, 0):
    subprocess.call(cmd)

# Generating combined event json file
cmd = [
    sys.executable,
    os.path.join(cwd, "libevents/scripts/combine.py"),
    generated_events_from_source_file,
    generated_events_common_enums_file,
    "--output",
    generated_events_combined_all_file,
]
if sys.version_info > (3, 0):
    subprocess.call(cmd)


# 检验合并的events_all.json文件
cmd = [
    sys.executable,
    os.path.join(cwd, "libevents/scripts/validate.py"),
    generated_events_combined_all_file,
]
if sys.version_info > (3, 0):
    subprocess.call(cmd)

# 创建压缩文件
# cmd = [
#     sys.executable,
#     os.path.join(cwd, "../../tools/compress.py"),
#     generated_events_combined_all_file,
# ]
# subprocess.call(cmd)

# Generating event header file
cmd = [
    sys.executable,
    os.path.join(cwd, "libevents/scripts/generate.py"),
    "--template",
    os.path.join(cwd, "libevents/libs/cpp/templates/events_generated.h.jinja"),
    "--output",
    cwd,
    generated_events_common_enums_file,
]
if sys.version_info > (3, 0):
    subprocess.call(cmd)


inc = [cwd]
src = ["events.cpp"]

objs = DefineGroup("pkg/events", src, depend=["PKG_USING_EVENTS"], CPPPATH=inc)

Return("objs")
