import os
import rtconfig
from building import *


cwd = GetCurrentDir()

inc = [cwd]
src = ["ObstacleAvoidance.cpp"]

objs = DefineGroup("pkg/avoidance", src, depend=["PKG_USING_AVOIDANCE"], CPPPATH=inc)


Return("objs")
