import os
import sys
import subprocess
from building import *

cwd = GetCurrentDir()

inc = []
src = Glob("*.cpp")

objs = DefineGroup("drv/tone_alarm", src, depend=["DRV_USING_TONE_ALARM"])

Return("objs")
