import os
import sys
import subprocess
from building import *

cwd = GetCurrentDir()


cmd = [
    sys.executable,
    os.path.join(cwd, "mavlink/pymavlink/tools/mavgen.py"),
    "--lang",
    "C",
    "--wire-protocol",
    "2.0",
    # --no-validate,
    # --strict-units,
    "--output",
    os.path.join(cwd, "mavlink/generated"),
    os.path.join(cwd, "mavlink/message_definitions/v1.0/common.xml"),
]

# subprocess.call(cmd)

inc = [
    cwd,
    os.path.join(cwd, "mavlink/generated"),
    os.path.join(cwd, "mavlink/generated/common"),
]
src = Glob("*.cpp", exclude="*Test.cpp") + Glob("mavlink.c")


if not GetDepend(["MAVLINK_USING_PARAM"]):
    SrcRemove(src, "mavlink_parameters.cpp")

if not GetDepend(["MAVLINK_USING_MISSION"]):
    SrcRemove(src, "mavlink_mission.cpp")

if not GetDepend(["MAVLINK_USING_SHELL"]):
    SrcRemove(src, "mavlink_shell.cpp")

if not GetDepend(["MAVLINK_USING_FTP"]):
    SrcRemove(src, "mavlink_ftp.cpp")

if not GetDepend(["MAVLINK_USING_LOG_DOWNLOAD"]):
    SrcRemove(src, "mavlink_log_handler.cpp")

if not GetDepend(["MAVLINK_USING_LOG_STREAM"]):
    SrcRemove(src, "mavlink_ulog.cpp")

if not GetDepend(["MAVLINK_USING_TIMESYNC"]):
    SrcRemove(src, "mavlink_timesync.cpp")

objs = DefineGroup(
    "tel/mavlink",
    src,
    depend=["TEL_USING_MAVLINK"],
    LOCAL_CPPPATH=inc,
    CFLAGS=" -Wno-address-of-packed-member",
    CXXFLAGS=" -Wno-address-of-packed-member",
)


Return("objs")
