import os
import sys
import subprocess
from building import *

cwd = GetCurrentDir()


cmd = [
    sys.executable,
    os.path.join(cwd, "mavlink/pymavlink/tools/mavgen.py"),
    "--lang",
    "c",
    "--wire-protocol",
    "2.0",
    # --no-validate,
    # --strict-units,
    "--output"
    os.path.join(cwd, "malvink"),
    os.path.join(cwd, "mavlink/message_definitions/v1.0/"),
]

subprocess.run(cmd)

inc = [cwd]
src = Glob("*.cpp", exclude="*Test.cpp")

objs = DefineGroup("tel/mavlink", src, depend=["TEL_USING_MAVLINk"])


Return("objs")
