import os
import rtconfig
from building import *

cwd = GetCurrentDir()
objs = []

src = Glob("*.cpp")
inc = [cwd]


if GetDepend(["BSP_USING_QEMU"]):
    defs = ["CONSTRAINED_FLASH", "CONSTRAINED_MEMORY"]
else:
    defs = []


objs += DefineGroup(name="app", src=src, depend=[], CPPPATH=inc, CPPDEFINES=defs)

for d in os.listdir(cwd):
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, "SConscript")):
        objs += SConscript(os.path.join(d, "SConscript"))

Return("objs")
