import os
import rtconfig
from building import *

objs = []

if GetDepend(["SYS_USING_HRTIMER_V2"]):
    cwd = GetCurrentDir()
    src = ["hrtimer.c"]

    if GetDepend(["HRT_USING_HARD_SYSTICK"]):
        src += ["hrt_hard_systick.c"]

    if GetDepend(["HRT_USING_HARD_TIMER"]):
        src += ["hrt_hard_timer.c"]

    inc = [cwd]
    objs += DefineGroup("lib/common", src, depend=[""], CPPPATH=inc)

    for d in os.listdir(cwd):
        path = os.path.join(cwd, d)
        if os.path.isfile(os.path.join(path, "SConscript")):
            objs += SConscript(os.path.join(d, "SConscript"))
else:
    objs = []

Return("objs")
