import os
import rtconfig
from building import *


cwd = GetCurrentDir()

inc = [cwd, os.path.join(cwd, "math/filter")]
src = []

objs = DefineGroup("lib/mathlib", src, depend=["PKG_USING_MATHLIB"], CPPPATH=inc)


Return("objs")
