import os
import rtconfig
from building import *

objs = []

if GetDepend(["PKG_USING_MATHLIB"]):
    cwd = GetCurrentDir()
    src = []

    inc = [cwd, os.path.join(cwd, "math/filter")]
    objs += DefineGroup("lib/mathlib", src, depend=[""], CPPPATH=inc)

    for d in os.listdir(cwd):
        path = os.path.join(cwd, d)
        if os.path.isfile(os.path.join(path, "SConscript")):
            objs += SConscript(os.path.join(d, "SConscript"))
else:
    objs = []

Return("objs")
