import os
import sys
import rtconfig
from building import *

objs = []

if GetDepend(["PKG_USING_WORKQUEUE"]):
    cwd = GetCurrentDir()
    src = Glob("*.cpp")
    inc = [cwd]

    objs += DefineGroup("pkg/workq", src, depend=[""], CPPPATH=inc)

    for d in os.listdir(cwd):
        path = os.path.join(cwd, d)
        if os.path.isfile(os.path.join(path, "SConscript")):
            # print(os.path.join(d, 'SConscript'))
            objs += SConscript(os.path.join(d, "SConscript"))
else:
    objs = []

Return("objs")
