import os
import sys
from building import *


cwd = GetCurrentDir()

inc = []
src = Glob("*.cpp", exclude="*Test.cpp")

objs = DefineGroup("fcs/vtol_att_control", src, depend=["FCS_USING_VTOL_ATT_CONTROL"])

Return("objs")
