import os
import sys
from building import *

objs = []

if GetDepend(["FCS_USING_VTOL_ATT_CONTROL"]):
    cwd = GetCurrentDir()
    src = Glob("*.cpp", exclude="*Test.cpp")

    objs = DefineGroup("fcs/vtol_att_control", src, depend=[""])
else:
    pass

Return("objs")
