import os
import rtconfig
from building import *

objs = []


cwd = GetCurrentDir()

inc = [cwd]
src = ["npfg.cpp"]

objs = DefineGroup("lib/control", src, depend=["PKG_USING_NPFG"], CPPPATH=inc)


Return("objs")
