import os
import rtconfig
from building import *


cwd = GetCurrentDir()

inc = [cwd]
src = ["hrtimer.c"]

if GetDepend(["HRT_USING_HARD_SYSTICK"]):
    src += ["hrt_hard_systick.c"]

if GetDepend(["HRT_USING_HARD_TIMER"]):
    src += ["hrt_hard_timer.c"]


objs = DefineGroup("lib/common", src, depend=["PKG_USING_HRTIMER_V2"], CPPPATH=inc)


Return("objs")
