import os
import rtconfig
from building import *

objs = []

if not GetDepend(["SOC_IMXRT1170_SERIES"]):
    Return("objs")

cwd = GetCurrentDir()

for d in os.listdir(cwd):
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, "SConscript")):
        objs += SConscript(os.path.join(d, "SConscript"))

Return("objs")
