import os
import rtconfig
from building import *


objs = []

# 添加当前文件夹下的代码
cwd = GetCurrentDir()
src = []
inc = [cwd]

objs += DefineGroup("lib/common", src, depend=[""], CPPPATH=inc)

for d in os.listdir(cwd):
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, "SConscript")):
        # print(os.path.join(d, 'SConscript'))
        objs += SConscript(os.path.join(d, "SConscript"))

Return("objs")
