import os
import sys
from building import *

cwd = GetCurrentDir()

inc = []
src = Glob("*.cpp", exclude="*Test.cpp")

objs = DefineGroup("fcs/rc_update", src, depend=["FCS_USING_RC_UPDATE"])

Return("objs")
