import os
import sys
from building import *

objs = []

if GetDepend(["FCS_USING_RC_UPDATE"]):
    cwd = GetCurrentDir()
    src = Glob("*.cpp", exclude="*Test.cpp")

    objs = DefineGroup("fcs/rc_update", src, depend=[""])
else:
    pass

Return("objs")
