import os
import sys
from building import *

cwd = GetCurrentDir()

inc = []
src = Glob("*.cpp") + Glob("FeasibilityChecker.cpp") + Glob("GeofenceBreachAvoidance/geofence_breach_avoidance.cpp")

objs = DefineGroup("fcs/navigator", src, depend=["FCS_USING_NAVIGATOR"])

Return("objs")
