import os
import sys
import subprocess
from building import *

cwd = GetCurrentDir()

inc = []
src = Glob("*.cpp")

objs = DefineGroup("drv/bmi055", src, depend=["DRV_USING_PWM_OUT"])

Return("objs")
