import os
import sys
import rtconfig
import subprocess
from building import *

objs = []
cwd = GetCurrentDir()


def gen_global_params():
    # 工程根目录
    prj_root = os.path.abspath(os.path.join(cwd, "../../"))
    # 搜索包含*_params.c文件的目录
    src_path = set()
    for root, dirs, files in os.walk(prj_root):
        for file in files:

            if (file.endswith("params.c") or file.endswith("parameters.c")) and "rtos" not in root:
                src_path.add(root)

    # 生成parameters.xml文件
    cmd = [
        sys.executable,
        os.path.join(cwd, "tools/process_params.py"),
        "--xml",
        File("#/build/parameters.xml").abspath,
        "--json",
        File("#/build/paramters.json").abspath,
        "--compress",
        "--inject-xml",
        os.path.join(cwd, "tools/parameters_injected.xml"),
        "--board",
        "nextpilot",
        # --verbose
        "--src-path",
    ] + list(src_path)

    subprocess.call(cmd)

    # 生成parameters.hpp文件
    cmd = [
        sys.executable,
        os.path.join(cwd, "tools/generate_params.py"),
        "--xml",
        File("#/build/parameters.xml").abspath,
        "--dest",
        os.path.join(cwd, "interface"),
    ]

    subprocess.call(cmd)


gen_global_params()

inc = [cwd, os.path.join(cwd, "interface"), os.path.join(cwd, "storage"), os.path.join(cwd, "wrapper")]
src = [
    "param_interface.c",
    "param_storage.c",
    "param.c",
]

if GetDepend(["PARAM_USING_STORAGE_FILE"]):
    src += ["storage/param_storage_file.c"]

if GetDepend(["PARAM_USING_STORAGE_FM25V02"]):
    src += ["storage/param_storage_fm25v02.c"]

if GetDepend(["PARAM_USING_GLOBAL_AUTOGEN"]):
    src += ["interface/param_global_autogen.cpp"]

if GetDepend(["PARAM_USING_LINKER_SECTION"]):
    src += ["interface/param_linker_section.cpp"]

if GetDepend(["PARAM_USING_SIMULINK_CAPI"]):
    src += ["interface/param_simulink_capi.cpp"]


objs = DefineGroup("pkg/param", src, depend=["PKG_USING_PARAM"], CPPPATH=inc)


Return("objs")
